openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: AI Agent API Support
    email: support@zegocloud.com

servers:
  - url: https://aigc-aiagent-api.zegotech.cn
    description: Unified access address (no regional distinction)
  - url: https://aigc-aiagent-api-sha.zegotech.cn
    description: Mainland China (Shanghai)
  - url: https://aigc-aiagent-api-hkg.zegotech.cn
    description: Hong Kong, Macao, and Taiwan (Hong Kong)
  - url: https://aigc-aiagent-api-fra.zegotech.cn
    description: Europe (Frankfurt)
  - url: https://aigc-aiagent-api-lax.zegotech.cn
    description: Western United States (California)
  - url: https://aigc-aiagent-api-bom.zegotech.cn
    description: Asia-Pacific (Mumbai)
  - url: https://aigc-aiagent-api-sgp.zegotech.cn
    description: Southeast Asia (Singapore)

tags:
  - name: agent-configuration-management

paths:
  /:
    post:
      tags:
        - agent-configuration-management
      summary: ListAgents
      description: By calling this API, you can obtain a list of available AI agents.
      operationId: list-agents
      parameters:
        - name: Action
          in: query
          description: |
            > API Prototype Parameter
            >
            > https://aigc-aiagent-api.zegotech.cn?Action=ListAgents
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [ListAgents]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ListAgentsRequest"
            example:
              Limit: 10
              Cursor: ""
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListAgentsResponse"
              example:
                Code: 0
                Message: "Success"
                RequestId: "8825223157230377926"
                Data:
                  Total: 10
                  Agents:
                    - AgentId: "Jacky"
                      Name: "Jacky"
                      LLM:
                        Url: "https://ark.cn-beijing.volces.com/api/v3/chat/completions"
                        ApiKey: "eexxxxxxxxxxxxxxx"
                        Model: "ep-xxxxxxxxxx"
                        SystemPrompt: "You are Jacky, an adult man, a companion assistant **created by ZEGOCLOUD**. knowledgeable in everything, intelligent, wise, enthusiastic, and friendly. \nDialogue requirements: 1. Dialogue with users according to the requirements of the persona. \n2.No more than 100 words."
                      TTS:
                        Vendor: "ByteDance"
                        Params:
                          app:
                            appid: "your_appid"
                            cluster: "volcano_tts"
                            token: "your_token"
                          audio:
                            voice_type: "your_voice_type"
                      ASR: {}
                  Cursor: "COAI"

components:
  schemas:
    ListAgentsRequest:
      type: object
      properties:
        Limit:
          type: integer
          description: The number of AI agent information entries to retrieve in one request. The value range is [0, 10]. If not filled or the value is 0, it defaults to 5. If the value is less than 0 or greater than 10, the API request will return an error.
          minimum: 0
          maximum: 10
          default: 5
          example: 10
        Cursor:
          type: string
          description: Pagination retrieval marker. Leave blank for the first request, then fill in the Cursor value returned from the previous response. When the returned Cursor is empty, it indicates that the list of AI agents has been fully retrieved.
          example: ""

    ListAgentsResponse:
      type: object
      properties:
        Code:
          type: integer
          description: Return code. 0 indicates success, other values indicate failure. For more information on error codes and response handling recommendations, please refer to [Return Codes](/aiagent-server/api-reference/return-codes).
          example: 0
        Message:
          type: string
          description: Explanation of the request result
          example: "Success"
        RequestId:
          type: string
          description: Request ID
          example: "8825223157230377926"
        Data:
          type: object
          properties:
            Total:
              type: integer
              description: Total number of AI agents that meet the query criteria
              example: 10
            Agents:
              type: array
              description: AI Agent list
              items:
                type: object
                properties:
                  AgentId:
                    type: string
                    description: AI agent unique identifier
                    example: "Jacky"
                  Name:
                    type: string
                    description: AI agent name
                    example: "Jacky"
                  LLM:
                    $ref: '../shared-components.yaml#/components/schemas/LLM'
                  TTS:
                    $ref: '../shared-components.yaml#/components/schemas/TTS'
                  ASR:
                    $ref: '../shared-components.yaml#/components/schemas/ASR'
            Cursor:
              type: string
              description: A non-empty value only indicates that there are still AI agent details not returned, and you need to set this field in the request parameter Cursor to fetch more AI agent information; an empty value indicates that all AI agent information has been returned.
              example: "COAI"
