openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: AI Agent API Support
    email: support@zegocloud.com

servers:
  - url: https://aigc-aiagent-api.zegotech.cn
    description: Unified access address (no regional distinction)
  - url: https://aigc-aiagent-api-sha.zegotech.cn
    description: Mainland China (Shanghai)
  - url: https://aigc-aiagent-api-hkg.zegotech.cn
    description: Hong Kong, Macao, and Taiwan (Hong Kong)
  - url: https://aigc-aiagent-api-fra.zegotech.cn
    description: Europe (Frankfurt)
  - url: https://aigc-aiagent-api-lax.zegotech.cn
    description: Western United States (California)
  - url: https://aigc-aiagent-api-bom.zegotech.cn
    description: Asia-Pacific (Mumbai)
  - url: https://aigc-aiagent-api-sgp.zegotech.cn
    description: Southeast Asia (Singapore)

tags:
  - name: agent-configuration-management

paths:
  /:
    post:
      tags:
        - agent-configuration-management
      summary: QueryAgents
      description: By calling this API, you can query AI agent information.
      operationId: query-agents
      parameters:
        - name: Action
          in: query
          description: |
            > API Prototype Parameter
            >
            > https://aigc-aiagent-api.zegotech.cn?Action=QueryAgents
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [QueryAgents]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/QueryAgentsRequest"
            example:
              AgentIds: ["Jacky", "Oliver"]
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/QueryAgentsResponse"
              example:
                Code: 0
                Message: "success"
                RequestId: "8825223157230377926"
                Data:
                  Agents:
                    - AgentId: "Jacky"
                      Name: "Jacky"
                      LLM:
                        Url: "https://ark.cn-beijing.volces.com/api/v3/chat/completions"
                        ApiKey: "eexxxxxxxxxxxxxxx"
                        Model: "ep-xxxxxxxxxx"
                        SystemPrompt: "You are Jacky, an adult man, a companion assistant **created by ZEGOCLOUD**. knowledgeable in everything, intelligent, wise, enthusiastic, and friendly."
                      TTS:
                        Vendor: "ByteDance"
                        Params:
                          app:
                            appid: "your_appid"
                            cluster: "volcano_tts"
                            token: "your_token"
                          audio:
                            voice_type: "your_voice_type"
                      ASR: {}

components:
  schemas:
    QueryAgentsRequest:
      type: object
      required:
        - AgentIds
      properties:
        AgentIds:
          type: array
          description: A list of registered AI agent IDs, with a maximum length of 10.
          maxItems: 10
          items:
            type: string
          example: ["Jacky", "Oliver"]

    QueryAgentsResponse:
      type: object
      properties:
        Code:
          type: integer
          description: Return code. 0 indicates success, other values indicate failure. For more information on error codes and response handling recommendations, please refer to [Return Codes](/aiagent-server/api-reference/return-codes).
          example: 0
        Message:
          type: string
          description: Explanation of the request result
          example: "Success"
        RequestId:
          type: string
          description: Request ID
          example: "8825223157230377926"
        Data:
          type: object
          properties:
            Agents:
              type: array
              description: AI Agent list
              items:
                type: object
                properties:
                  AgentId:
                    type: string
                    description: AI Agent unique identifier
                    example: "Jacky"
                  Name:
                    type: string
                    description: AI Agent name
                    example: "Jacky"
                  LLM:
                    $ref: '../shared-components.yaml#/components/schemas/LLM'
                  TTS:
                    $ref: '../shared-components.yaml#/components/schemas/TTS'
                  ASR:
                    $ref: '../shared-components.yaml#/components/schemas/ASR'
