openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: AI Agent API Support
    email: support@zegocloud.com

servers:
  - url: https://aigc-aiagent-api.zegotech.cn
    description: Unified access address (no regional distinction)
  - url: https://aigc-aiagent-api-sha.zegotech.cn
    description: Mainland China (Shanghai)
  - url: https://aigc-aiagent-api-hkg.zegotech.cn
    description: Hong Kong, Macao, and Taiwan (Hong Kong)
  - url: https://aigc-aiagent-api-fra.zegotech.cn
    description: Europe (Frankfurt)
  - url: https://aigc-aiagent-api-lax.zegotech.cn
    description: Western United States (California)
  - url: https://aigc-aiagent-api-bom.zegotech.cn
    description: Asia-Pacific (Mumbai)
  - url: https://aigc-aiagent-api-sgp.zegotech.cn
    description: Southeast Asia (Singapore)

tags:
  - name: agent-configuration-management

paths:
  /:
    post:
      tags:
        - agent-configuration-management
      summary: RegisterAgent
      description: By calling this API, you can register an AI agent (Agent) for creating AI agent instances.
      operationId: register-agent
      x-ratelimit-limit: 10
      x-ratelimit-window: 1
      parameters:
        - name: Action
          in: query
          description: |
            > API Prototype Parameter
            >
            > https://aigc-aiagent-api.zegotech.cn?Action=RegisterAgent
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [RegisterAgent]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterAgentRequest"
            example:
              AgentId: "xiaozhi"
              Name: "Jacky"
              LLM:
                Url: "https://ark.cn-beijing.volces.com/api/v3/chat/completions"
                ApiKey: "zego_test"
                Model: "doubao-1-5-lite-32k-250115"
                SystemPrompt: "You are Jacky, an adult man, a companion assistant **created by ZEGOCLOUD**. knowledgeable in everything, intelligent, wise, enthusiastic, and friendly."
              TTS:
                Vendor: "ByteDance"
                Params:
                  app:
                    appid: "zego_test"
                    token: "zego_test"
                    cluster: "volcano_tts"
                  audio:
                    voice_type: "zh_female_qingxinnvsheng_mars_bigtts"
              ASR:
                HotWord: "即构科技|10"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegisterAgentResponse"

components:
  schemas:
    RegisterAgentRequest:
      type: object
      required:
        - AgentId
        - LLM
        - TTS
      properties:
        AgentId:
          type: string
          description: |
            Only supports numbers, English characters, and the following special characters: !#$%&()+-:;\<=.>?@[]^_\{}|~,.
          maxLength: 128
          example: "Jacky"
        Name:
          type: string
          description: AI Agent name, with a maximum length of 256 bytes.
          maxLength: 256
          example: "Jacky"
        LLM:
          $ref: '../shared-components.yaml#/components/schemas/LLM'
        TTS:
          $ref: '../shared-components.yaml#/components/schemas/TTS'
        ASR:
          $ref: '../shared-components.yaml#/components/schemas/ASR'

    RegisterAgentResponse:
      type: object
      properties:
        Code:
          type: integer
          description: Return code. 0 indicates success, other values indicate failure. For more information on error codes and response handling recommendations, please refer to [Return Codes](/aiagent-server/api-reference/return-codes).
          example: 0
        Message:
          type: string
          description: Explanation of the request result
          example: "Success"
        RequestId:
          type: string
          description: Request ID
          example: "8825223157230377926"
