openapi: 3.0.0
info:
  title: Real-time Voice/Video Shared Components
  version: 1.0.0

# 共享的服务器配置（RTC 产品）
servers:
  - url: https://rtc-api.zego.im
    description: 统一接入地址（不区分区域）
  - url: https://rtc-api-sha.zego.im
    description: 中国大陆（上海）
  - url: https://rtc-api-hkg.zego.im
    description: 港澳台（香港）
  - url: https://rtc-api-fra.zego.im
    description: 欧洲（法兰克福）
  - url: https://rtc-api-lax.zego.im
    description: 美西（加州）
  - url: https://rtc-api-bom.zego.im
    description: 亚太（孟买）
  - url: https://rtc-api-sgp.zego.im
    description: 东南亚（新加坡）

components:
  parameters:
    # Re-export ZEGO global shared parameters for convenient local reference
    AppId:
      $ref: "../../../../../../snippets/common/zh/openapi/zego-shared-components.yaml#/components/parameters/AppId"
    SignatureNonce:
      $ref: "../../../../../../snippets/common/zh/openapi/zego-shared-components.yaml#/components/parameters/SignatureNonce"
    Timestamp:
      $ref: "../../../../../../snippets/common/zh/openapi/zego-shared-components.yaml#/components/parameters/Timestamp"
    SignatureVersion:
      $ref: "../../../../../../snippets/common/zh/openapi/zego-shared-components.yaml#/components/parameters/SignatureVersion"
    Signature:
      $ref: "../../../../../../snippets/common/zh/openapi/zego-shared-components.yaml#/components/parameters/Signature"

    # Local extension to ZEGO shared parameters
    IsTest:
      name: IsTest
      in: query
      description: |
        是否为测试环境。取值如下：
        - true（忽略大小写）：测试环境
        - false（忽略大小写）：正式环境（默认值）
        针对 2021-11-16 及之前创建的项目为必填参数，其余情况可不填写。
      required: false
      schema:
        type: string
        enum: ["true", "false"]
        default: "false"

