openapi: 3.0.0
info:
  title: Real-time Voice/Video Shared Components
  version: 1.0.0

# 共享的服务器配置（RTC 产品）
servers:
  - url: https://rtc-api.zego.im
    description: 统一接入地址（不区分区域）
  - url: https://rtc-api-sha.zego.im
    description: 中国大陆（上海）
  - url: https://rtc-api-hkg.zego.im
    description: 港澳台（香港）
  - url: https://rtc-api-fra.zego.im
    description: 欧洲（法兰克福）
  - url: https://rtc-api-lax.zego.im
    description: 美西（加州）
  - url: https://rtc-api-bom.zego.im
    description: 亚太（孟买）
  - url: https://rtc-api-sgp.zego.im
    description: 东南亚（新加坡）

components:
  parameters:
    # Re-export ZEGO global shared parameters for convenient local reference
    AppId:
      $ref: "../../../../../snippets/common/zh/openapi/zego-shared-components.yaml#/components/parameters/AppId"
    SignatureNonce:
      name: SignatureNonce
      in: query
      description: 💡公共参数。16 位 16 进制随机字符串（8 字节随机数的 hex 编码）。生成算法可参考 <a href="/real-time-video-server/api-reference/accessing-server-apis#signature-example">签名示例</a>。
      required: true
      schema:
        type: string
    Timestamp:
      name: Timestamp
      in: query
      description: 💡公共参数。当前 Unix 时间戳，单位为秒。生成算法可参考 <a href="/real-time-video-server/api-reference/accessing-server-apis#signature-example">签名示例</a>，最多允许 10 分钟的误差。
      required: true
      schema:
        type: integer
        format: int64
    SignatureVersion:
      $ref: "../../../../../snippets/common/zh/openapi/zego-shared-components.yaml#/components/parameters/SignatureVersion"
    Signature:
      name: Signature
      in: query
      description: 💡公共参数。签名，用于验证请求的合法性。请参考[签名机制](/real-time-video-server/api-reference/accessing-server-apis#signature-mechanism)生成。
      required: true
      schema:
        type: string

