openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: AI Agent API Support
    email: support@zegocloud.com

servers:
  - url: https://aigc-aiagent-api.zegotech.cn
    description: 统一接入地址（不区分区域）
  - url: https://aigc-aiagent-api-sha.zegotech.cn
    description: 中国大陆（上海）

tags:
  - name: agent-instance-control

paths:
  /:
    post:
      tags:
        - agent-instance-control
      summary: send-agent-instance-llm
      description: 本接口可用于，以用户身份主动调用 LLM 服务，并基于 LLM 的响应内容，以智能体身份主动调用 TTS 服务，向用户发送语音消息。(1. 当调用此接口时，若会话中的智能体正在说话，则该智能体的说话进程会被打断；2. 调用本接口传入的文本信息不会记录在会话历史消息中，也不会通过 RTC 房间消息下发。但 LLM 生成的回复会被记录在会话历史消息中并且会通过 RTC 房间消息下发。)
      operationId: sendAgentInstanceLLM
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://aigc-aiagent-api.zegotech.cn?Action=SendAgentInstanceLLM
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [SendAgentInstanceLLM]
          style: form
          explode: true
        # 引用共享的参数
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SendAgentInstanceLLMRequest"
            example:
              AgentInstanceId: "1907755175297171456"
              Text: "今天天气怎么样？"
      responses:
        "200":
          description: 发送成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SendAgentInstanceLLMResponse"
              example:
                Code: 0
                Message: "Succeed"
                RequestId: "1843985617336143872"
        "400":
          description: 请求错误
          content:
            application/json:
              schema:
                $ref: '../shared-components.yaml#/components/schemas/ErrorResponse'

components:
  schemas:
    SendAgentInstanceLLMRequest:
      type: object
      required:
        - AgentInstanceId
        - Text
      properties:
        AgentInstanceId:
          type: string
          description: 智能体实例的唯一标识，通过 [创建智能体实例](/aiagent-server/api-reference/agent-instance-management/create-agent-instance) 接口的响应参数获取。
          example: "1907755175297171456"
        Text:
          type: string
          description: 发送给 LLM 服务的文本内容
          example: "今天天气怎么样？"
        SystemPrompt:
          type: string
          description: 是否需要临时修改本次对话的智能体系统提示（prompt），若需要则填写本字段。若填空，则不改动本轮对话的 system prompt。
          example: "你是一个友好的天气助手"

    SendAgentInstanceLLMResponse:
      type: object
      properties:
        Code:
          type: integer
          description: 返回码，0 表示成功，其他值表示失败。详情请参考 [返回码](/aiagent-server/api-reference/return-codes) 说明。
          example: 0
        Message:
          type: string
          description: 请求结果说明
          example: "Succeed"
        RequestId:
          type: string
          description: 请求 ID
          example: "1843985617336143872"
