openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: AI Agent API Support
    email: support@zegocloud.com

servers:
  - url: https://aigc-aiagent-api.zegotech.cn
    description: 统一接入地址（不区分区域）
  - url: https://aigc-aiagent-api-sha.zegotech.cn
    description: 中国大陆（上海）

tags:
  - name: agent-instance-control

paths:
  /:
    post:
      tags:
        - agent-instance-control
      summary: SendAgentInstanceTTS
      description: 本接口可用于主动调用 TTS 服务，以智能体身份向用户发送语音消息。(1. 当调用此接口时，若会话中的智能体正在说话，则该智能体的说话进程会被打断；2. 调用本接口传入的文本消息，会根据 AddHistory 参数决定是否被记录在会话消息历史之中，作为上下文输入给 LLM，同时该消息还会通过 RTC 房间消息下发。)
      operationId: send-agent-instance-tts
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://aigc-aiagent-api.zegotech.cn?Action=SendAgentInstanceTTS
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [SendAgentInstanceTTS]
          style: form
          explode: true
        # 引用共享的参数
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SendAgentInstanceTTSRequest"
            example:
              AgentInstanceId: "1907755175297171456"
              Text: "尊敬的开发者你好，欢迎使用 ZEGO RTC 共建实时互动世界。"
      responses:
        "200":
          description: 发送成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SendAgentInstanceTTSResponse"

components:
  schemas:
    SendAgentInstanceTTSRequest:
      type: object
      required:
        - AgentInstanceId
        - Text
      properties:
        AgentInstanceId:
          type: string
          description: 智能体实例的唯一标识，通过 [创建智能体实例](/aiagent-server/api-reference/agent-instance-management/create-agent-instance) 接口的响应参数获取。
          example: "1907755175297171456"
        Text:
          type: string
          description: 用于 TTS 的文本内容，最大不超过 300 个字符。
          maxLength: 300
          example: "尊敬的开发者你好，欢迎使用 ZEGO RTC 共建实时互动世界。"
        AddHistory:
          type: boolean
          description: 是否将文本消息记录在会话消息历史之中，作为上下文输入给 LLM。
          default: true
          example: true
        InterruptMode:
          type: integer
          description: |
            智能体说话时被用户语音打断的模式：
            - 0: 立即打断。如果在 AI 说话时用户说话，那么 AI 将被立刻打断，停止说话（默认）。
            - 1: 不打断。如果在 AI 说话时用户说话，那么 AI 不会被影响直到内容说完。
          default: 0
          example: 0

    SendAgentInstanceTTSResponse:
      type: object
      properties:
        Code:
          type: integer
          description: 返回码，0 表示成功，其他值表示失败。详情请参考 [返回码](/aiagent-server/api-reference/return-codes) 说明。
          example: 0
        Message:
          type: string
          description: 请求结果说明
          example: "Succeed"
        RequestId:
          type: string
          description: 请求 ID
          example: "1843985617336143872"
