openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact: { name: Real-time Voice/Video API Support, email: support@zegocloud.com }

tags:
  - name: media-service

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags: [media-service]
      summary: CreateCDNTransferRule
      description: |
        调用本接口启动旁路推流任务，可将 RTC 流旁路转推至指定 CDN 直播地址，建议在推流之前调用。

        如果开发者不再需要将流转推至 CDN，请参考 [停止旁路推流](!media/DeleteCDNTransferRule)。
        
        <Warning title="注意">
        若您是 RTC 转推 CDN、或混流转推 CDN，ZEGO 服务器会自动帮您进行 CDN 鉴权，您无需额外进行 CDN 鉴权。
        </Warning>
        <br/>
        以下请求参数列表仅列出了接口请求参数和部分公共参数，完整公共参数列表请参考 完整公共参数列表请参考 [调用方式](./../accessing-server-apis.mdx#公共请求参数) 中的 “公共请求参数”。

        <Note title="说明">
        
        测试环境下（详见 <a target="_blank" href="./../accessing-server-apis.mdx#公共请求参数">调用方式</a> 中的 “公共参数” 中的 IsTest 的参数说明），流 ID 需要加上 “zegotest-AppId-” 前缀。例如，流 ID 为 “test”，在 AppId 为 “123456789” 的测试环境下，流 ID 应为 “zegotest-123456789-test”。
        
        </Note>
      operationId: create-cdn-transfer-rule
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://rtc-api.zego.im?Action=CreateCDNTransferRule
          required: true
          schema: { type: string, enum: [CreateCDNTransferRule] }
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/IsTest'
        - name: StreamId
          in: query
          required: true
          schema: { type: string }
          description: 流 ID。
        - name: CDNUrl
          in: query
          required: false
          schema: { type: string }
          description: |
            转推的 CDN 地址，必须是 RTMP 格式。
            
            使用时，请对该参数内容进行 UrlEncode。
        - name: Sequence
          in: query
          required: true
          schema: { type: string }
          description: |
            请求序列号。

            > **注意**
            >
            > 对于同一个流 StreamId，连续 10 秒内，必须保证发出的该 StreamId 的请求序列号是严格递增的；避免服务端收到请求的时序不一致而导致操作错乱。

            如果没有并发场景，推荐使用时间戳（毫秒级别）。
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateCDNTransferRuleResponse'

components:
  schemas:
    CreateCDNTransferRuleResponse:
      type: object
      properties:
        Code: 
          type: integer
          format: int32
          description: |
            返回码。
            以下仅列出了接口业务逻辑相关的部分返回码，完整返回码请参考 [全局返回码](!global_return_code)。
            <table>
              <thead>
                <tr><th>返回码</th><th>说明</th><th>处理建议</th></tr>
              </thead>
              <tbody>
                <tr><td>5000、5001、5002、5006、30003</td><td>内部错误。</td><td>请联系 ZEGO 技术支持处理。</td></tr>
                <tr><td>5003</td><td>鉴权失败。</td><td>请检查签名 Signature 是否正确。</td></tr>
                <tr><td>5004</td><td>无效的 CDN 地址。</td><td>请检查请求参数 CDNUrl 是否正确。</td></tr>
                <tr><td>5005</td><td>无效请求。</td><td>请联系 ZEGO 技术支持处理。</td></tr>
                <tr><td>5007、30002</td><td>接口调用频率过高。</td><td>请降低接口请求频率。</td></tr>
                <tr><td>30001</td><td>无效的 CDN 地址。</td><td>请检查请求参数 CDNUrl 是否正确。</td></tr>
                <tr><td>30004</td><td>参数 isTest 错误。</td><td>请检查公共请求参数 isTest 是否正确。</td></tr>
                <tr><td>30005</td><td>无效的 AppId。</td><td>请检查 AppId 是否正确。</td></tr>
                <tr><td>30009</td><td>无效的 StreamId，流名不规范。</td><td>请检查 StreamId 是否符合流名编码规范。</td></tr>
              </tbody>
            </table>
          example: 0
        Message: 
          type: string
          description: 操作结果描述
          example: "ok"
        RequestId: 
          type: string
          description: 请求 ID
          example: "918334131114317411"
        Data:
          type: object
          description: 响应数据
          example: null

