openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact: { name: Real-time Voice/Video API Support, email: support@zegocloud.com }

tags:
  - name: media-service

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags: [media-service]
      summary: CreateCDNTransferRule
      description: 创建一个 CDN 旁路分发规则。
      operationId: create-cdn-transfer-rule
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://rtc-api.zego.im?Action=CreateCDNTransferRule
          required: true
          schema: { type: string, enum: [CreateCDNTransferRule] }
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/IsTest'
        - name: TransferType
          in: query
          required: true
          description: 分发类型，1：RTMP；2：HLS；3：FLV。
          schema: { type: integer, format: int32, enum: [1,2,3] }
        - name: SrcStreamId
          in: query
          required: true
          schema: { type: string }
          description: 源流 ID。
        - name: SrcStreamUrl
          in: query
          required: false
          schema: { type: string }
          description: 源流 URL。
        - name: DestUrl
          in: query
          required: true
          schema: { type: string }
          description: 目标 URL。
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateCDNTransferRuleResponse'

components:
  schemas:
    CreateCDNTransferRuleResponse:
      type: object
      properties:
        Code: { type: integer, format: int32 }
        Message: { type: string }
        RequestId: { type: string }

