openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact: { name: Real-time Voice/Video API Support, email: support@zegocloud.com }

tags:
  - name: media-service

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags: [media-service]
      summary: ForbidRTCStreams
      description: |
        调用本接口批量禁止 RTC 推流，可以批量禁止指定流 ID 推送到 RTC 服务。禁止推流操作会向正在推流的客户端和正在拉流的客户端发送推流被禁止的通知。通常用于开发者需要通过服务端临时中断某终端推流时使用。

        推流客户端接收推流被服务端禁止的通知使用 ZEGO Express SDK 回调接口：

        <table>

          <tbody><tr>
            <th rowspan="2">平台</th>
            <th colspan="2">ZegoExpress SDK</th>
            <th colspan="2">LiveRoom SDK</th>
          </tr>
          <tr>
            <th>接口</th>
            <th>错误码</th>
            <th>接口</th>
            <th>错误码</th>
          </tr>
          <tr>
            <td>iOS/macOS</td>
            <td>onPublisherStateUpdate</td>
            <td>1003025</td>
            <td>onPublishStateUpdate</td>
            <td>12301011</td>
          </tr>
          <tr>
            <td>Android</td>
            <td>onPublisherStateUpdate</td>
            <td>1003025</td>
            <td>onPublishStateUpdate</td>
            <td>12301011</td>
          </tr>
          <tr>
            <td>Windows</td>
            <td>onPublisherStateUpdate</td>
            <td>1003025</td>
            <td>OnPublishStateUpdate</td>
            <td>12301011</td>
          </tr>
        </tbody></table>



        拉流客户端接收所拉流被服务端禁止的通知使用 ZEGO Express SDK 回调接口：


        <table>

          <tbody><tr>
            <th rowspan="2">平台</th>
            <th colspan="2">ZegoExpress SDK</th>
            <th colspan="2">LiveRoom SDK</th>
          </tr>
          <tr>
            <th>接口</th>
            <th>错误码</th>
            <th>接口</th>
            <th>错误码</th>
          </tr>
          <tr>
            <td>iOS/macOS</td>
            <td>onPlayerStateUpdate</td>
            <td>1004025</td>
            <td>onPlayStateUpdate</td>
            <td>12301011</td>
          </tr>
          <tr>
            <td>Android</td>
            <td>onPlayerStateUpdate</td>
            <td>1004025</td>
            <td>onPlayStateUpdate</td>
            <td>12301011</td>
          </tr>
          <tr>
            <td>Windows</td>
            <td>onPlayerStateUpdate</td>
            <td>1004025</td>
            <td>OnPlayStateUpdate</td>
            <td>12301011</td>
          </tr>
        </tbody></table>

        <Warning title="注意">
        调用本接口后，正在推送的音视频流会被禁止推送，同时流 ID 被记录到后台数据库；不存在的流直接记录到后台数据库，接口正常返回成功。
        </Warning>

        <Note title="调用频率限制">同一个 AppID 下所有房间：20 次/秒（测试环境：5 次/秒）</Note>



        <Note title="说明">
        测试环境下（详见 IsTest 公共参数说明），流 ID 需要加上 “zegotest-AppId-” 前缀。例如，流 ID 为 “test”，在 AppId 为 “123456789” 的测试环境下，流 ID 应为 “zegotest-123456789-test”。
        </Note>
      operationId: forbid-rtc-streams
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://rtc-api.zego.im?Action=ForbidRTCStreams
          required: true
          schema: { type: string, enum: [ForbidRTCStreams] }
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/IsTest'
        - name: StreamId[]
          in: query
          description: 流 ID 列表，最大支持 20 个流 ID。
          required: true
          schema:
            type: array
            items: { type: string }
          style: form
          explode: true
        - name: Sequence
          in: query
          required: true
          schema: { type: string }
          description: |
            请求序列号。

            > **注意**
            >
            > 对于同一个流 StreamId，连续 10 秒内，必须保证发出的该 StreamId 的请求序列号是严格递增的；避免服务端收到请求的时序不一致而导致操作错乱。

            如果没有并发场景，推荐使用时间戳（毫秒级别）。
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbidRTCStreamsResponse'

components:
  schemas:
    ForbidRTCStreamsResponse:
      type: object
      properties:
        Code:
          type: integer
          format: number
          description: |
            返回码。
            以下仅列出了接口业务逻辑相关的部分返回码，完整返回码请参考 [全局返回码](/real-time-video-server/api-reference/return-codes)。
            <table>
              <thead>
                <tr><th>返回码</th><th>说明</th><th>处理建议</th></tr>
              </thead>
              <tbody>
                <tr><td>30002</td><td>接口调用频率过高。</td><td>请降低接口请求频率。</td></tr>
                <tr><td>30003</td><td>内部错误。</td><td>请联系 ZEGO 技术支持处理。</td></tr>
                <tr><td>30004</td><td>参数 isTest 错误。</td><td>请检查公共请求参数 isTest 是否正确。</td></tr>
                <tr><td>30005</td><td>无效的 AppId。</td><td>请检查 AppId 是否正确。</td></tr>
                <tr><td>30006</td><td>无效的 StreamId 列表。</td><td>请检查 StreamId[] 是否正确。</td></tr>
                <tr><td>42003</td><td>批量禁用直播失败。</td><td>请重试，重试无效请联系 ZEGO 技术支持。</td></tr>
              </tbody>
            </table>
          example: 0
        Message:
          type: string
          description: 操作结果描述
          example: "ok"
        RequestId:
          type: string
          description: 请求 ID
          example: "1929203990360298509"
        Data:
          type: object
          description: 响应数据
          example: null

