openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact: { name: Real-time Voice/Video API Support, email: support@zegocloud.com }

tags:
  - name: media-service

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags: [media-service]
      summary: ForbidRTCStreams
      description: 批量禁止指定流 ID 推送到 RTC 服务。
      operationId: forbid-rtc-streams
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://rtc-api.zego.im?Action=ForbidRTCStreams
          required: true
          schema: { type: string, enum: [ForbidRTCStreams] }
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/IsTest'
        - name: StreamId
          in: query
          description: 流 ID 列表，最大支持 20 个流 ID。
          required: true
          schema:
            type: array
            items: { type: string }
            minItems: 1
            maxItems: 20
          style: form
          explode: true
        - name: Sequence
          in: query
          required: true
          schema: { type: string }
          description: 请求序列号。并发情况下须在 10 秒内严格递增。
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbidRTCStreamsResponse'

components:
  schemas:
    ForbidRTCStreamsResponse:
      type: object
      properties:
        Code: { type: integer, format: int32 }
        Message: { type: string }
        RequestId: { type: string }
        Data: { type: object }

