openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact: { name: Real-time Voice/Video API Support, email: support@zegocloud.com }

tags:
  - name: media-service

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags: [media-service]
      summary: ForbidCDNLiveStream
      description: |
        调用本接口禁止 CDN 推流，适用直推 CDN 场景。如需应用于转推 CDN 场景，请使用 [停止旁路推流](/real-time-video-server/api-reference/media-service/delete-cdn-transfer-rule) 接口。

        <Warning title="注意">
        首次使用本接口，需要联系 ZEGO 技术支持进行配置。
        </Warning>
        <Note title="调用频率限制">同一个 AppID 下所有房间：20 次/秒</Note>
      operationId: forbid-cdn-live-stream
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://rtc-api.zego.im?Action=ForbidCDNLiveStream
          required: true
          schema: { type: string, enum: [ForbidCDNLiveStream] }
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/IsTest'
        - name: StreamId
          in: query
          required: true
          schema: { type: string }
          description: 流 ID。
        - name: ResumeTime
          in: query
          required: false
          schema: { type: string }
          description: |
            恢复流的时间。UTC 格式，例如：2018-11-29T19:00:00Z。<br />
            注意：仅网宿支持该参数，默认禁推 1 天，且最长支持禁推 30 天。例如，若禁推 30 天，则禁播时长会设置为：当前时间 +30 天。
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbidCDNLiveStreamResponse'

components:
  schemas:
    ForbidCDNLiveStreamResponse:
      type: object
      properties:
        Code: 
          type: integer
          format: number
          description: |
            返回码。
            以下仅列出了接口业务逻辑相关的部分返回码，完整返回码请参考 [全局返回码](/real-time-video-server/api-reference/return-codes)。
            <table>
              <thead>
                <tr><th>返回码</th><th>说明</th><th>处理建议</th></tr>
              </thead>
              <tbody>
                <tr><td>0</td><td>请求成功。</td><td>-</td></tr>
                <tr><td>1</td><td>请求失败。</td><td>-</td></tr>
                <tr><td>2</td><td>参数错误。</td><td>-</td></tr>
                <tr><td>3</td><td>鉴权失败。</td><td>请检查鉴权参数是否正确。</td></tr>
              </tbody>
            </table>
          example: 0
        Message: 
          type: string
          description: 操作结果描述
          example: "success"
        RequestId: 
          type: string
          description: 请求 ID
          example: "4113829426153229963"
        Data:
          type: array
          description: 响应数据
          items:
            type: object
            properties:
              CdnType:
                type: string
                description: |
                  CDN 类型：
                  - ws：网宿
                  - aliyun：阿里云
                  - tencent：腾讯云
                  - huawei：华为云
                example: "ws"
              CdnResult:
                type: string
                description: CDN 处理结果
                example: "success append purge tasks"

