openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact: { name: Real-time Voice/Video API Support, email: support@zegocloud.com }

tags:
  - name: media-service

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags: [media-service]
      summary: QueryForbidCDNLiveStream
      description: 查询流在 CDN 拉流侧的禁播状态。
      operationId: query-forbid-cdn-live-stream
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://rtc-api.zego.im?Action=QueryForbidCDNLiveStream
          required: true
          schema: { type: string, enum: [QueryForbidCDNLiveStream] }
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/IsTest'
        - name: StreamId
          in: query
          required: true
          schema: { type: string }
          description: 流 ID。
        - name: Sequence
          in: query
          required: true
          schema: { type: string }
          description: 请求序列号。并发情况下须在 10 秒内严格递增。
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryForbidCDNLiveStreamResponse'

components:
  schemas:
    QueryForbidCDNLiveStreamResponse:
      type: object
      properties:
        Code: { type: integer, format: int32 }
        Message: { type: string }
        RequestId: { type: string }
        Data:
          type: object
          properties:
            ForbidState: { type: integer, format: int32, description: "0：未禁播；1：禁播中" }

