openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact: { name: Real-time Voice/Video API Support, email: support@zegocloud.com }

tags:
  - name: media-service

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags: [media-service]
      summary: ResumeCDNLiveStream
      description: |
        调用本接口恢复 CDN 推流，适用直推 CDN 场景。如需应用于转推 CDN 场景，请使用 [启动旁路推流](!media/CreatCDNTransferRule) 接口。

        <Warning title="注意">
        首次使用本接口，需要联系 ZEGO 技术支持进行配置。
        </Warning>
      operationId: resume-cdn-live-stream
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://rtc-api.zego.im?Action=ResumeCDNLiveStream
          required: true
          schema: { type: string, enum: [ResumeCDNLiveStream] }
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/IsTest'
        - name: StreamId
          in: query
          required: true
          schema: { type: string }
          description: 流 ID。
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResumeCDNLiveStreamResponse'

components:
  schemas:
    ResumeCDNLiveStreamResponse:
      type: object
      properties:
        Code: 
          type: integer
          format: int32
          description: |
            返回码。
            以下仅列出了接口业务逻辑相关的部分返回码，完整返回码请参考 [全局返回码](!global_return_code)。
            <table>
              <thead>
                <tr><th>返回码</th><th>说明</th><th>处理建议</th></tr>
              </thead>
              <tbody>
                <tr><td>0</td><td>请求成功。</td><td>-</td></tr>
                <tr><td>1</td><td>请求失败。</td><td>-</td></tr>
                <tr><td>2</td><td>参数错误。</td><td>-</td></tr>
                <tr><td>3</td><td>鉴权失败。</td><td>请检查鉴权参数是否正确。</td></tr>
              </tbody>
            </table>
          example: 0
        Message: 
          type: string
          description: 操作结果描述
          example: "success"
        RequestId: 
          type: string
          description: 请求 ID
          example: "3162938795049910659"
        Data: 
          type: object
          description: 响应数据
          properties:
            CdnType:
              type: string
              description: |
                CDN 类型：
                - ws：网宿
                - aliyun：阿里云
                - tencent：腾讯云
                - huawei：华为云
              example: "ws"
            CdnResult:
              type: string
              description: CDN 处理结果
              example: "success append purge tasks"

