openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact: { name: Real-time Voice/Video API Support, email: support@zegocloud.com }

tags:
  - name: media-service

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags: [media-service]
      summary: RTMPDispatchV2
      description: |
        调用本接口可以发起 RTMP 推拉流调度，支持 "pull" 和 "push" 两种调度模式。

        当您需要自行通过 RTMP 协议，从 ZEGO 音视频云进行直播流的推流或拉流时，可以通过本接口获取 RTMP 的推流或拉流节点。开发者在客户端传入流 ID（StreamId）、调度模式（Type）、客户端 IP（ClientIP）和序列号（Sequence）后，ZEGO 媒体服务器（RTC 服务）返回调度结果集，供客户推拉流。

        例如，当通过 OBS 等第三方推流工具进行 RTMP 推流时，需要进行推流调度；当需要第三方播放器拉 RTMP 流进行播放时，需要进行拉流调度。

        <Warning title="注意">
        首次使用本接口，需要联系 ZEGO 技术支持进行配置。
        </Warning>
        <Note title="调用频率限制">同一个 AppID 下：40 次/秒</Note>
        ## 旧版接口使用说明

        <Accordion title="使用 RTMPDispatch 访问 ZEGO 服务端" defaultOpen="false">
        <Note title="说明">


        **RTMPDispatchV2（推荐）** 和 **RTMPDispatch** 的区别是，访问 ZEGO 服务端时：

        - 使用的是 `RTMPDispatchV2`，ZEGO 服务端返回的 Data 数据为 URL 形式。
        - 使用的是 `RTMPDispatch`，ZEGO 服务端返回的 Data 数据为 IP Port 形式。

        </Note>



        请求地址：`https://rtc-api.zego.im/?Action=RTMPDispatch`

        响应示例：

        ```json
        {
            "Code":0,
            "Message":"ok",
            "RequestId":"5094436160208407316",
            "Data":[
                "81.69.49.115:1935"
            ]
        }
        ```
        </Accordion>
        <br/>

        <Note title="说明">
        测试环境下（详见 IsTest 公共参数说明），流 ID 需要加上 "zegotest-AppId-" 前缀。例如，流 ID 为 "test"，在 AppId 为 "123456789" 的测试环境下，流 ID 应为 "zegotest-123456789-test"。
        </Note>
      operationId: rtpm-dispatch
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://rtc-api.zego.im?Action=RTMPDispatchV2
          required: true
          schema: { type: string, enum: [RTMPDispatchV2] }
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/IsTest'
        - name: StreamId
          in: query
          required: true
          schema: { type: string }
          description: |
            流 ID，长度不超过 256 的字符串。
            - 流 ID 由您自己定义。
            - 在推流时，需要在整个 AppID 内全局唯一，若出现在同一个 AppID 内，不同的用户各推了一条流且流名相同，将会导致后推流的用户推流失败。
            - 仅支持数字，英文字符 和 '-', '_'。
        - name: Sequence
          in: query
          required: true
          schema: { type: Int64 }
          description: 请求序列号；仅用于请求对帐，推荐使用时间戳（毫秒级别）。
        - name: Type
          in: query
          required: true
          schema: { type: string }
          description: |
            调度模式：
            - pull：获取 RTMP 的拉流节点
            - push：获取 RTMP 的推流节点
        - name: ClientIP
          in: query
          required: false
          schema: { type: string }
          description: |
            非必选，如有，则传入客户端 IP 地址，例如：119.23.242.129。

            > **注意**
            >
            > 当前不支持 IPv6 格式的 IP 地址。
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RTMPDispatchV2Response'

components:
  schemas:
    RTMPDispatchV2Response:
      type: object
      properties:
        Code:
          type: integer
          format: number
          description: |
            返回码。
            以下仅列出了接口业务逻辑相关的部分返回码，完整返回码请参考 [全局返回码](/real-time-video-server/api-reference/return-codes)。
            <table>
              <thead>
                <tr><th>返回码</th><th>说明</th><th>处理建议</th></tr>
              </thead>
              <tbody>
                <tr><td>1010、30002</td><td>接口调用频率过高。</td><td>请降低接口请求频率。</td></tr>
                <tr><td>1001</td><td>调度失败。</td><td>请联系 ZEGO 技术支持处理。</td></tr>
                <tr><td>1002</td><td>推流节点为空。</td><td>请联系 ZEGO 技术支持处理。</td></tr>
                <tr><td>1003</td><td>拉流节点为空。</td><td>请联系 ZEGO 技术支持处理。</td></tr>
                <tr><td>1005</td><td>App 不在线。</td><td>请联系 ZEGO 技术支持处理。</td></tr>
                <tr><td>1006</td><td>无效参数。</td><td>请联系 ZEGO 技术支持处理。</td></tr>
                <tr><td>30003</td><td>内部错误。</td><td>请联系 ZEGO 技术支持处理。</td></tr>
                <tr><td>30004</td><td>参数 isTest 错误。</td><td>请检查公共请求参数 isTest 是否正确。</td></tr>
                <tr><td>30005</td><td>无效的 AppId。</td><td>请检查 AppId 是否正确。</td></tr>
                <tr><td>30009</td><td>无效的 StreamId，流名不规范。</td><td>请检查 StreamId 是否符合流名编码规范。</td></tr>
                <tr><td>30010</td><td>无效的调度动作。</td><td>请检查 Type 是否正确。</td></tr>
                <tr><td>30011</td><td>无效的客户端 IP 地址。</td><td>请检查 ClientIP 是否正确。</td></tr>
              </tbody>
            </table>
          example: 0
        Message:
          type: string
          description: 操作结果描述
          example: "ok"
        RequestId:
          type: string
          description: 请求 ID
          example: "5094436160208407316"
        Data:
          type: object
          description: |
            RTMP 推流或拉流节点。

            > **说明**
            >
            > 获取此节点后，请在 2 小时内发起推流或拉流，否则可能导致节点被占用或下线。因此，建议每次进行 RTMP 推拉流时，都调用本接口获得最新的节点。
          example: ["rtmp://81.69.49.115:1935/1540531164/caodantest"]