openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: Real-time Voice/Video API Support
    email: support@zegocloud.com

tags:
  - name: stream-mixing

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags:
        - stream-mixing
      summary: GetMixTaskInfo
      description: |
        根据指定混流任务的 taskid 查询相关信息。

        以下请求参数列表仅列出了接口请求参数和部分公共参数，完整公共参数列表请参考 完整公共参数列表请参考 [调用方式](./../accessing-server-apis.mdx#公共请求参数) 中的 “公共请求参数”。
      operationId: get-mix-task-info
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://rtc-api.zego.im?Action=GetMixTaskInfo
          required: true
          schema:
            type: string
            enum: [GetMixTaskInfo]
          style: form
          explode: true
        # 公共参数（Query）
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/IsTest'
        # 业务参数
        - name: TaskId
          in: query
          description: 任务 ID，混流任务的唯一标识。
          required: true
          schema:
            type: string
      responses:
        "200":
          description: 操作成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMixTaskInfoResponse'

components:
  schemas:
    GetMixTaskInfoResponse:
      type: object
      properties:
        Code: 
          type: integer
          format: int32
          description: |
            以下仅列出了接口业务逻辑相关的部分返回码，完整返回码请参考 [全局返回码](!global_return_code)。
            
            <table>
            <thead>
              <tr><th>返回码</th><th>说明</th><th>处理建议</th></tr>
            </thead>
            <tbody>
              <tr><td>0</td><td>请求成功。</td><td>-</td></tr>
              <tr><td>110200001</td><td>失败。</td><td>建议重试。一般是网络错误异常导致。</td></tr>
              <tr><td>110200004</td><td>解析输入参数失败。</td><td>请检查混流参数是否正确。</td></tr>
              <tr><td>110200194</td><td>混流请求过载。</td><td>请求过于频繁，请稍后再试。</td></tr>
              <tr><td>110209001</td><td>混流任务不存在。</td><td>请核查该混流任务是否正在进行。如果混流任务实际正在进行，请联系 ZEGO 技术支持。</td></tr>
            </tbody>
            </table>
          example: 0
        Message: 
          type: string
          description: 操作结果描述。
          example: "success"
        RequestId: 
          type: string
          description: 请求 ID。
          example: "1864314306034131629"
        Data:
          type: object
          description: 响应数据。
          properties:
            TaskInfo:
              type: object
              description: 混流任务信息。
              properties:
                TaskId: 
                  type: string
                  description: 混流任务 ID。
                  example: "task_test_123"
                MixDuration: 
                  type: integer
                  format: int32
                  description: 混流任务持续时长，单位秒。
                  example: 13

