openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: Real-time Voice/Video API Support
    email: support@zegocloud.com

tags:
  - name: stream-mixing

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    post:
      tags:
        - stream-mixing
      summary: StopCloudTranscode
      description: |
        调用本接口，停止单流转码任务。

        “客户端”基于转码模板触发的单流转码介绍，请参考 [单流转码](/real-time-video-android-java/live-streaming/single-stream-transcoding)；
        “服务端”的相关回调，请参考 [单流转码开始回调](/real-time-video-server/callback/transcoding/on-demand-transcoding-started) 和 [单流转码停止回调](/real-time-video-server/callback/transcoding/on-demand-transcoding-stopped)。

         <Note title="调用频率限制">100 次/秒</Note>
      operationId: stop-cloud-transcode
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://rtc-api.zego.im?Action=StopCloudTranscode
          required: true
          schema:
            type: string
            enum: [StopCloudTranscode]
          style: form
          explode: true
        # 公共参数（Query）
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StopCloudTranscodeRequest'
      responses:
        "200":
          description: 操作成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StopCloudTranscodeResponse'

components:
  schemas:
    StopCloudTranscodeRequest:
      type: object
      required: [TaskId, UserId]
      properties:
        TaskId:
          type: string
          description: 任务 ID，单流转码任务的唯一标识，由开发者自定义。
          example: "2213699902971205739"
        UserId:
          type: string
          description: 用户 ID。当开启单流转码任务归属时，停止某个 TaskId 的转码任务必须输入 <a href="!Start_single_stream_transcoding" target="_blank">开始单流转码</a> 任务时指定的 UserId。
          example: "456"
        Sequence:
          type: integer
          format: int
          description: 转码任务的序列号，用于保证时序，同个任务的参数修改需要保证序列号的递增。
    StopCloudTranscodeResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int
          description: |
            以下仅列出了接口业务逻辑相关的部分返回码，完整返回码请参考 [全局返回码](/real-time-video-server/api-reference/return-codes)。

            <table>
            <thead>
              <tr><th>返回码</th><th>说明</th><th>处理建议</th></tr>
            </thead>
            <tbody>
              <tr><td>110200002</td><td>输入参数错误。</td><td>请参考 Message 信息处理。</td></tr>
              <tr><td>110200151</td><td>单流转码任务失败。</td><td>请重试，或联系 ZEGO 技术支持处理。</td></tr>
            </tbody>
            </table>
          example: 0
        Message:
          type: string
          description: 操作结果描述。
          example: "success"
        RequestId:
          type: string
          description: 请求 ID。
          example: "8472822294336370476"

