openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: Real-time Voice/Video API Support
    email: support@zegocloud.com

tags:
  - name: stream-mixing

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    post:
      tags:
        - stream-mixing
      summary: StopAutoMix
      description: |
        调用本接口停止 `音频` 自动混流任务。相关回调请参考 [混流结束回调](!Callback/Callback_StopMix)。
        <Note title="说明">
        使用 POST 请求方法传递参数时：
        - Body 中的参数直接传 JsonObject 格式即可，无需序列化为 String 格式。
        - Headers 中，设置 “Content-type” 为 “application/json”。
        </Note>
        以下请求参数列表仅列出了接口请求参数和部分公共参数，完整公共参数列表请参考 完整公共参数列表请参考 [调用方式](./../accessing-server-apis.mdx#公共请求参数) 中的 “公共请求参数”。
      operationId: stop-auto-mix
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://rtc-api.zego.im?Action=StopAutoMix
          required: true
          schema:
            type: string
            enum: [StopAutoMix]
          style: form
          explode: true
        # 公共参数（Query）
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/IsTest'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StopAutoMixRequest'
      responses:
        "200":
          description: 操作成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StopAutoMixResponse'

components:
  schemas:
    StopAutoMixRequest:
      type: object
      required: [TaskId, RoomId]
      properties:
        TaskId: 
          type: string
          description: 混流任务 ID，需要和开始混流传入的 TaskId 保持一致。
          example: "2213699902971205739"
        RoomId: 
          type: string
          description: 房间 ID。
          example: "room123"
        Sequence: 
          type: integer
          format: int32
          description: 混流任务的序列号，用于保证时序，同个任务的参数修改需要保证序列号的递增。
          example: 1
        UserId: 
          type: string
          description: 用户 ID。当开启混流任务归属时停止某个 TaskId 的混流任务必须输入开始混流任务时指定的 UserId。
    StopAutoMixResponse:
      type: object
      properties:
        Code: 
          type: integer
          format: int32
          description: |
            以下仅列出了接口业务逻辑相关的部分返回码，完整返回码请参考 [全局返回码](!global_return_code)。
            
            <table>
            <thead>
              <tr><th>返回码</th><th>说明</th><th>处理建议</th></tr>
            </thead>
            <tbody>
              <tr><td>110200001</td><td>失败。</td><td>请重试。</td></tr>
              <tr><td>110200002</td><td>输入参数错误。</td><td>请参考 Message 信息处理。</td></tr>
              <tr><td>110200003</td><td>鉴权失败。</td><td>请确认鉴权信息是否正确或过期，详情请参考 <a href="!Making_API_Requests/Making_API_Requests#5" target="_blank">调用方式</a> 中的 "3 签名机制"。</td></tr>
              <tr><td>110200004</td><td>解析输入参数失败。</td><td>请检查混流参数是否正确。</td></tr>
            </tbody>
            </table>
          example: 0
        Message: 
          type: string
          description: 操作结果描述。
          example: "success"
        RequestId:
          type: string
          description: 请求 ID。
          example: "6351841974556802202"

