openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: Real-time Voice/Video API Support
    email: support@zegocloud.com

tags:
  - name: room

servers:
  $ref: '../../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags:
        - room
      summary: DelForbidUserRule
      description: |
        删除用户封禁规则。当某些用户封禁规则失效、无用或规则总条数超过上限时，可以通过该接口删除用户封禁规则。

        删除后，您可以通过 [查询用户封禁规则](./describe-forbid-user-rules.mdx) 查看对应的用户封禁规则是否删除成功。

        <Note title="调用频率限制">同一个 AppID 下所有房间：10 次/秒。</Note>

        <Warning title="注意">
        每个 RuleType 所支持设置的最大条数限制不同，如果您不需要某些规则，请及时调用本接口进行清理。此外，ZEGO 也会不定期清理数据库中的**已失效**的封禁规则。
        </Warning>
      operationId: del-forbid-user-rule
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://rtc-api.zego.im?Action=DelForbidUserRule
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [DelForbidUserRule]
          style: form
          explode: true
        # 公共参数
        - $ref: '../../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../../shared-components.yaml#/components/parameters/SignatureVersion'
        # 业务参数
        - name: RuleType
          in: query
          description: |
            所需删除的封禁规则类型：
            - 1：通过 IP 地址封禁用户；
            - 2：通过 RoomId 封禁用户；
            - 3：通过 UserId 封禁用户；
            - 4：通过 RoomId 和 UserId 封禁用户。

          required: true
          schema:
            type: integer
            format: int32
            enum: [1, 2, 3, 4]
        - name: IP
          in: query
          description: IP 地址。RuleType 为 1 时必填。
          required: false
          schema:
            type: string
        - name: RoomId
          in: query
          description: 房间 ID。RuleType 为 2、4 时必填。
          required: false
          schema:
            type: string
        - name: UserId
          in: query
          description: 用户 ID。RuleType 为 3、4 时必填。
          required: false
          schema:
            type: string
      responses:
        "200":
          description: 操作成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DelForbidUserRuleResponse'

components:
  schemas:
    DelForbidUserRuleResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int32
          example: 0
          description: |
            返回码。以下仅列出了接口业务逻辑相关的部分返回码，完整返回码请参考 [全局返回码](/real-time-video-server/api-reference/return-codes)。

            <table>
              <thead>
                <tr>
                  <th>返回码</th>
                  <th>说明</th>
                  <th>处理建议</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>0</td>
                  <td>请求成功。</td>
                  <td>-</td>
                </tr>
                <tr>
                  <td>1</td>
                  <td>请求失败。</td>
                  <td>请联系 ZEGO 技术支持处理。</td>
                </tr>
                <tr>
                  <td>2</td>
                  <td>输入参数错误。</td>
                  <td>-</td>
                </tr>
                <tr>
                  <td>9</td>
                  <td>未开通当前接口的使用权限。</td>
                  <td>请联系 ZEGO 技术支持处理。</td>
                </tr>
                <tr>
                  <td>206</td>
                  <td>App 请求 QPS 过高被限制。</td>
                  <td>降低请求频率，或联系 ZEGO 技术支持提高 QPS 限制阈值。</td>
                </tr>
                <tr>
                  <td>50123</td>
                  <td>当前处于有效期内的封禁规则条数超过限制。</td>
                  <td>请减少规则条数。</td>
                </tr>
              </tbody>
            </table>
        Message:
          type: string
          example: success
          description: 操作结果描述。
        RequestId:
          type: string
          example: TestRequestId1675674022729915000
          description: 请求 ID。
