openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: Real-time Voice/Video API Support
    email: support@zegocloud.com

tags:
  - name: room

servers:
  $ref: '../../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags:
        - room
      summary: DescribeForbidUserRules
      description: |
        查询用户封禁规则。
        <Note title="调用频率限制">同一个 AppID 下所有房间：10 次/秒。</Note>
        <Warning title="注意">
        调用 `DescribeForbidUserRules` 接口，可以查询到当前处于有效期内的规则，也可以查询到已失效的规则。**请注意，ZEGO 会不定期清理数据库中的已失效的封禁规则，调用本接口查询得到的失效规则列表可能不完整。**
        </Warning>
      operationId: describe-forbid-user-rules
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://rtc-api.zego.im?Action=DescribeForbidUserRules
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [DescribeForbidUserRules]
          style: form
          explode: true
        # 公共参数
        - $ref: '../../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../../shared-components.yaml#/components/parameters/IsTest'
        # 业务参数
        - name: RuleType
          in: query
          description: |
            需要查询的封禁规则类型：
            - 1：通过 IP 地址封禁用户；
            - 2：通过 RoomId 封禁用户；
            - 3：通过 UserId 封禁用户；
            - 4：通过 RoomId 和 UserId 封禁用户。

          required: true
          schema:
            type: integer
            format: int32
            enum: [1, 2, 3, 4]
      responses:
        "200":
          description: 操作成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DescribeForbidUserRulesResponse'
              example:
                Code: 0
                Message: success
                RequestId: TestRequestId1675674022729915000
                Data:
                  RuleList:
                    - RuleType: 2
                      IP: ""
                      RoomId: room1
                      UserId: ""
                      DisabledPrivilegeList: [1, 2]
                      ExpireTime: 1704282648
                    - RuleType: 2
                      IP: ""
                      RoomId: room2
                      UserId: ""
                      DisabledPrivilegeList: [1]
                      ExpireTime: 1704282648

components:
  schemas:
    DescribeForbidUserRulesResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int32
          description: |
            返回码。以下仅列出了接口业务逻辑相关的部分返回码，完整返回码请参考 [全局返回码](/real-time-video-server/api-reference/return-codes)。

            <table>
              <thead>
                <tr>
                  <th>返回码</th>
                  <th>说明</th>
                  <th>处理建议</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>0</td>
                  <td>请求成功。</td>
                  <td>-</td>
                </tr>
                <tr>
                  <td>1</td>
                  <td>请求失败。</td>
                  <td>请联系 ZEGO 技术支持处理。</td>
                </tr>
                <tr>
                  <td>2</td>
                  <td>输入参数错误。</td>
                  <td>-</td>
                </tr>
                <tr>
                  <td>9</td>
                  <td>未开通当前接口的使用权限。</td>
                  <td>请联系 ZEGO 技术支持处理。</td>
                </tr>
                <tr>
                  <td>206</td>
                  <td>App 请求 QPS 过高被限制。</td>
                  <td>降低请求频率，或联系 ZEGO 技术支持提高 QPS 限制阈值。</td>
                </tr>
                <tr>
                  <td>50123</td>
                  <td>当前处于有效期内的封禁规则条数超过限制。</td>
                  <td>请减少规则条数。</td>
                </tr>
              </tbody>
            </table>
        Message:
          type: string
          description: 操作结果描述。
        RequestId:
          type: string
          description: 请求 ID。
        Data:
          type: object
          properties:
            RuleList:
              type: array
              description: 用户封禁规则列表。
              items:
                $ref: '#/components/schemas/ForbidUserRule'

    ForbidUserRule:
      type: object
      properties:
        RuleType:
          type: integer
          format: int32
          description: 封禁规则类型：1：通过 IP 地址封禁用户；2：通过 RoomId 封禁用户；3：通过 UserId 封禁用户；4：通过 RoomId 和 UserId 封禁用户。
          enum: [1, 2, 3, 4]
        IP:
          type: string
          description: IP 地址。RuleType 为 1 时，该参数有值。
        RoomId:
          type: string
          description: 房间 ID。RuleType 为 2、4 时，该参数有值。
        UserId:
          type: string
          description: 用户 ID。RuleType 为 3、4 时，该参数有值。
        DisabledPrivilegeList:
          type: array
          description: 规则封禁用户所能使用的功能：1：登录；2：推流。
          items:
            type: integer
            format: int32
            enum: [1, 2]
        ExpireTime:
          type: integer
          format: int64
          description: 用户封禁规则的过期时间，Unix 时间戳，单位：秒。
