openapi: 3.0.0
info:
  title: ZEGOCLOUD Shared Components
  version: 1.0.0

components:
  # 共享的参数定义
  parameters:
    AppId:
      name: AppId
      in: query
      description: 💡Public parameter. Application ID, assigned by ZEGOCLOUD. Get it from the [ZEGOCLOUD Admin Console](https://console.zegocloud.com/).
      required: true
      schema:
        type: integer
        format: uint32

    SignatureNonce:
      name: SignatureNonce
      in: query
      description: 💡Public parameter. A 16-character hexadecimal random string (hex encoding of 8-byte random number). Refer to [Signature sample code](#signature-sample-code) for how to generate.
      required: true
      schema:
        type: string

    Timestamp:
      name: Timestamp
      in: query
      description: 💡Public parameter. Current Unix timestamp, in seconds. Refer to [Signature sample code](#signature-sample-code) for how to generate, with a maximum error of 10 minutes.
      required: true
      schema:
        type: integer
        format: int64

    SignatureVersion:
      name: SignatureVersion
      in: query
      description: 💡Public parameter. Signature version number.
      required: true
      schema:
        type: string
        default: "2.0"
        enum: ["2.0"]

    Signature:
      name: Signature
      in: query
      description: 💡Public parameter. Signature, used to verify the legitimacy of the request. Refer to [Signing the requests](/real-time-video-server/api-reference/accessing-server-apis#signature-mechanism) for how to generate an API request signature.
      required: true
      schema:
        type: string

  # 共享的Schema定义
  schemas:
    ErrorResponse:
      type: object
      properties:
        Code:
          type: integer
          description: 错误码
          example: 400
        Message:
          type: string
          description: 错误信息
          example: "Invalid request parameters"
        RequestId:
          type: string
          description: 请求 ID
          example: "3151527792559699733"