openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact: { name: Real-time Voice/Video API Support, email: support@zegocloud.com }

tags:
  - name: cdn

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags: [cdn]
      summary: DescribeMediaTask
      description: |
        本接口用于查询 [合并媒体文件](/real-time-video-server/api-reference/cdn/merge-media)、[开始点播转码](/real-time-video-server/api-reference/cdn/start-on-demand-transcoding) 及 [开始点播截图](/real-time-video-server/api-reference/cdn/media-thumbnails) 任务的详细信息，作为 [媒体文件合并完成回调](/real-time-video-server/callback/cdn/merge-media-completed) 和 [点播转码完成回调](/real-time-video-server/callback/cdn/on-demand-transcoding-completed) 的补充。

        本接口支持查询“合并任务”、“转码任务”及“截图任务”的进度；任务完成后，也可以通过本接口获取合并文件或转码文件的播放地址。
        <Note title="调用频率限制">同一个 AppID 下所有房间：20 次/秒</Note>
      operationId: describe-media-task
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://rtc-api.zego.im?Action=DescribeMediaTask
          required: true
          schema: { type: string, enum: [DescribeMediaTask] }
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/IsTest'
        - name: TaskId
          in: query
          required: true
          schema: { type: string }
          description: 需要查询的任务 ID，即 <a href="!Media_File/MergeMedia" target="_blank">合并媒体文件</a>、<a href="!Start_onDemand_transcoding" target="_blank">开始点播转码</a> 及 <a href="!MediaThumbnails" target="_blank">开始点播截图</a> 接口响应参数中 Data 内携带的 TaskId。
        - name: Vendor
          in: query
          required: true
          schema: { type: string, enum: [Tencent, Huawei] }
          description: |
            <p>可能的取值及对应的 CDN 厂商：</p><ul><li>Tencent：腾讯云。<li>Huawei：华为云。</li>
            注意：当前华为云只支持查询截图任务，暂不支持查询合并任务和转码任务。</li></ul>
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DescribeMediaTaskResponse'

components:
  schemas:
    DescribeMediaTaskResponse:
      type: object
      properties:
        Code: 
          type: integer
          format: int32
          description: |
              以下仅列出了接口业务逻辑相关的部分返回码，完整返回码请参考 [全局返回码](/real-time-video-server/api-reference/return-codes)。
              <table>
                <thead>
                  <tr><th>返回码</th><th>说明</th><th>处理建议</th></tr>
                </thead>
                <tbody>
                  <tr><td>0</td><td>请求成功。</td><td>-</td></tr>
                  <tr><td>2</td><td>输入参数错误。</td><td>-</td></tr>
                  <tr><td>3</td><td>未开通相关权限。</td><td>请联系 ZEGO 技术支持。</td></tr>
                  <tr><td>4</td><td>CDN 类型不匹配。</td><td>请检查参数。</td></tr>
                  <tr><td>5</td><td>配置错误。</td><td>请联系 ZEGO 技术支持。</td></tr>
                  <tr><td>6</td><td>请求过于频繁。</td><td>请稍后重试。</td></tr>
                  <tr><td>7</td><td>鉴权失败。</td><td>请检查鉴权参数是否正确。</td></tr>
                  <tr><td>1000</td><td>请求失败。</td><td>请联系 ZEGO 技术支持。</td></tr>
                </tbody>
              </table>
          example: 0
        Message: 
          type: string
          description: 操作结果描述
          example: "success"
        RequestId: 
          type: string
          description: 请求 ID，由 ZEGO 服务端返回
          example: ""
        Data:
          type: object
          description: 响应数据
          properties:
            Tencent:
              type: object
              description: 腾讯云返回内容（Vendor 取值为 Tencent 时返回）
              properties:
                TaskId: 
                  type: string
                  description: 查询的任务 ID
                  example: "1400341231-ComposeMedia-6fdfc967d7eb12f5e9b27f52519f1afatt0"
                Event: 
                  type: string
                  description: |
                    任务的事件类型，返回值为：
                    - compose：媒体文件合并
                    - transcode：媒体文件点播转码
                    - SnapshotByTimeOffset：时间点截图任务
                    - SampleSnapshot：时间间隔截图任务
                  example: "compose"
                Status: 
                  type: string
                  description: |
                    任务状态：
                    - WAITING：等待中
                    - PROCESSING：处理中
                    - FINISH：已完成
                    - FAIL：失败
                  example: "FINISH"
                FileId: 
                  type: string
                  description: 媒体文件合并或转码后的文件 ID，与检索媒体信息接口响应参数中 Data 内携带的 FileId 相同
                  example: "xxxxxxxx"
                ReplayUrl: 
                  type: string
                  description: 媒体文件合并或转码后的文件回放地址，不超过 1024 字节
                  example: "https://xxxxx-xxxxxxxx.zego.im/xxxxxxxx/xxxxxxx/xxxxxx.mp4"
                RequestId: 
                  type: string
                  description: 唯一请求 ID，由请求参数 Vendor 取值对应的 CDN 厂商（即腾讯云）返回，定位问题时需要提供该次请求的 RequestId
                  example: "6aac31f4-xxxx-xxxx-xxxx-5cc10ce11a49"
                Message: 
                  type: string
                  description: 媒体文件任务失败的错误信息
                  example: ""
                ThumbnailsUrl:
                  type: array
                  description: 点播截图任务生成的文件链接
                  items: { type: string }
                  example: 
                    - "http://vod-tc-restorefile.zego.im/43b7b075vodtranscq1500030200/93172bfa1397757897438985100/sampleSnapshot/sampleSnapshot_10_0.jpg"
                    - "http://vod-tc-restorefile.zego.im/43b7b075vodtranscq1500030200/93172bfa1397757897438985100/sampleSnapshot/sampleSnapshot_10_2.jpg"
            Huawei:
              type: object
              description: 华为云返回内容（Vendor 取值为 Huawei 时返回）
              properties:
                TaskId: 
                  type: string
                  description: 查询的任务 ID
                  example: "289665200"
                Status: 
                  type: string
                  description: |
                    任务状态：
                    - NO_TASK：任务不存在
                    - WAITING：等待处理
                    - PROCESSING：处理中
                    - SUCCEEDED：已完成
                    - FAILED：失败
                    - CANCELED：任务取消
                  example: "SUCCEEDED"
                CreateTime: 
                  type: string
                  description: 任务开始时间，云厂商服务端 UTC 时间
                  example: "20241118065429"
                EndTime: 
                  type: string
                  description: 任务结束时间，云厂商服务端 UTC 时间
                  example: "20241118065430"
                FileName:
                  type: array
                  description: 点播截图任务生成的文件
                  items: { type: string }
                  example:
                    - "record/pickrecord/command_record/clarechen_test/0.jpg"
                    - "record/pickrecord/command_record/clarechen_test/10.jpg"

