openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact: { name: Real-time Voice/Video API Support, email: support@zegocloud.com }

tags:
  - name: cdn

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags: [cdn]
      summary: DescribeMediaTask
      description: 查询合并/转码/截图任务详情。
      operationId: describe-media-task
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://rtc-api.zego.im?Action=DescribeMediaTask
          required: true
          schema: { type: string, enum: [DescribeMediaTask] }
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/IsTest'
        - name: TaskId
          in: query
          required: true
          schema: { type: string }
          description: 任务 ID。
        - name: Vendor
          in: query
          required: true
          schema: { type: string, enum: [Tencent, Huawei] }
          description: CDN 厂商。
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DescribeMediaTaskResponse'

components:
  schemas:
    DescribeMediaTaskResponse:
      type: object
      properties:
        Code: { type: integer, format: int32 }
        Message: { type: string }
        RequestId: { type: string }
        Data:
          type: object
          properties:
            Tencent:
              type: object
              properties:
                TaskId: { type: string }
                Event: { type: string }
                Status: { type: string }
                FileId: { type: string }
                ReplayUrl: { type: string }
                RequestId: { type: string }
                Message: { type: string }
                ThumbnailsUrl:
                  type: array
                  items: { type: string }
            Huawei:
              type: object
              properties:
                TaskId: { type: string }
                Status: { type: string }
                CreateTime: { type: string }
                EndTime: { type: string }
                FileName:
                  type: array
                  items: { type: string }

