openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact: { name: Real-time Voice/Video API Support, email: support@zegocloud.com }

tags:
  - name: cdn

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags: [cdn]
      summary: MergeMedia
      description: 合并媒体文件。
      operationId: merge-media
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://rtc-api.zego.im?Action=MergeMedia
          required: true
          schema: { type: string, enum: [MergeMedia] }
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/IsTest'
        - name: Vendor
          in: query
          required: true
          schema: { type: string, enum: [Tencent, Huawei] }
          description: CDN 厂商。
        - name: Format
          in: query
          required: false
          schema: { type: string }
        - name: Type
          in: query
          required: false
          schema: { type: string, enum: ["0","1"] }
        - name: InputFileId
          in: query
          required: false
          description: 合并文件 ID 列表（Type=0 时有效且必填）。
          schema:
            type: array
            items: { type: string }
            minItems: 1
          style: form
          explode: true
        - name: HandleMediaArgs.FileId
          in: query
          required: false
          description: 裁剪后合并的文件 ID 列表（Type=1 时有效且必填）。按 N 从 0 起递增传入。
          schema:
            type: array
            items: { type: string }
            minItems: 1
          style: form
          explode: true
        - name: HandleMediaArgs.StartTime
          in: query
          required: false
          description: 对应文件开始裁剪时间（秒）。按 N 从 0 起递增传入。
          schema:
            type: array
            items: { type: number }
          style: form
          explode: true
        - name: HandleMediaArgs.EndTime
          in: query
          required: false
          description: 对应文件结束裁剪时间（秒）。按 N 从 0 起递增传入。
          schema:
            type: array
            items: { type: number }
          style: form
          explode: true
        - name: OutputFileName
          in: query
          required: false
          schema: { type: string }
        - name: ExpireTime
          in: query
          required: false
          schema: { type: integer, format: int32 }
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MergeMediaResponse'

components:
  schemas:
    MergeMediaResponse:
      type: object
      properties:
        Code: { type: integer, format: int32 }
        Message: { type: string }
        RequestId: { type: string }
        Data:
          type: object
          properties:
            Tencent:
              type: object
              properties:
                TaskId: { type: string }
                RequestId: { type: string }
            Huawei:
              type: object
              properties:
                TaskId: { type: string }
                RequestId: { type: string }

