openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact: { name: Real-time Voice/Video API Support, email: support@zegocloud.com }

tags:
  - name: cdn

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags: [cdn]
      summary: SearchMedia
      description: 检索媒体信息。
      operationId: search-media
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://rtc-api.zego.im?Action=SearchMedia
          required: true
          schema: { type: string, enum: [SearchMedia] }
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/IsTest'
        - name: Vendor
          in: query
          required: true
          schema: { type: string, enum: [Tencent, Ws, Huawei] }
          description: CDN 厂商。
        - name: NamePrefix
          in: query
          schema: { type: string }
          required: false
        - name: StartTime
          in: query
          required: false
          schema: { type: integer, format: int64 }
        - name: EndTime
          in: query
          required: false
          schema: { type: integer, format: int64 }
        - name: PageSize
          in: query
          required: false
          schema: { type: integer, format: int32 }
        - name: PageNumber
          in: query
          required: false
          schema: { type: integer, format: int32 }
        - name: FileId
          in: query
          required: false
          description: 文件 ID 列表，最多 10 个。
          schema:
            type: array
            items: { type: string }
            minItems: 1
            maxItems: 10
          style: form
          explode: true
        - name: StreamId
          in: query
          required: false
          description: CDN 录制流 ID 列表，最多 10 个。
          schema:
            type: array
            items: { type: string }
            minItems: 1
            maxItems: 10
          style: form
          explode: true
        - name: Marker
          in: query
          required: false
          schema: { type: string }
        - name: MaxKeys
          in: query
          required: false
          schema: { type: integer, format: int32, minimum: 1, maximum: 1000, default: 1000 }
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchMediaResponse'

components:
  schemas:
    SearchMediaResponse:
      type: object
      properties:
        Code: { type: integer, format: int32 }
        Message: { type: string }
        RequestId: { type: string }
        Data:
          type: object
          properties:
            Tencent:
              type: object
              properties:
                RequestId: { type: string }
                TotalCount: { type: integer, format: int32 }
                MediaInfoSet:
                  type: array
                  items:
                    type: object
                    properties:
                      FileId: { type: string }
                      BasicInfo:
                        type: object
                        properties:
                          Name: { type: string }
                          Description: { type: string }
                          CreateTime: { type: string }
                          UpdateTime: { type: string }
                          ExpireTime: { type: string }
                          ClassId: { type: integer, format: int32 }
                          ClassName: { type: string }
                          ClassPath: { type: string }
                          CoverUrl: { type: string }
                          Type: { type: string }
                          MediaUrl: { type: string }
                          SourceInfo: { type: object }
                          SourceType: { type: string }
                          SourceContext: { type: string }
                          StorageRegion: { type: string }
                          Vid: { type: string }
                          Category: { type: string }
                          Status: { type: string }
                          StorageClass: { type: string }
                      TranscodeInfo:
                        type: object
                        properties:
                          TranscodeSet:
                            type: array
                            items:
                              type: object
                              properties:
                                Url: { type: string }
                                Definition: { type: integer, format: int32 }
                                Bitrate: { type: integer, format: int32 }
                                Height: { type: integer, format: int32 }
                                Width: { type: integer, format: int32 }
                                Size: { type: integer, format: int64 }
                                Duration: { type: number }
                                Md5: { type: string }
                                Container: { type: string }
                                VideoStreamSet:
                                  type: array
                                  items:
                                    type: object
                                    properties:
                                      Bitrate: { type: integer, format: int32 }
                                      Height: { type: integer, format: int32 }
                                      Width: { type: integer, format: int32 }
                                      Codec: { type: string }
                                      Fps: { type: integer, format: int32 }
                                      CodecTag: { type: string }
                                      DynamicRangeInfo:
                                        type: object
                                        properties:
                                          Type: { type: string }
                                          HDRType: { type: string }
                                AudioStreamSet:
                                  type: array
                                  items:
                                    type: object
                                    properties:
                                      Bitrate: { type: integer, format: int32 }
                                      SamplingRate: { type: integer, format: int32 }
                                      Codec: { type: string }
                                      DigitalWatermarkType: { type: string }
                                      CopyRightWatermarkText: { type: string }
            Huawei:
              type: object
              properties:
                NextMarker: { type: string }
                Keys:
                  type: array
                  items:
                    type: object
                    properties:
                      ETag: { type: string }
                      Key: { type: string }
                      LastModified: { type: string }
                      Size: { type: integer, format: int64 }
                      MediaUrl: { type: string }
            Ws:
              type: object
              properties:
                NextMarker: { type: string }
                Keys:
                  type: array
                  items:
                    type: object
                    properties:
                      ETag: { type: string }
                      Key: { type: string }
                      LastModified: { type: string }
                      Size: { type: integer, format: int64 }
                      MediaUrl: { type: string }

