openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact: { name: Real-time Voice/Video API Support, email: support@zegocloud.com }

tags:
  - name: cdn

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags: [cdn]
      summary: TranscodeMedia
      description: |
        用户进行 CDN 录制时，可以将录制好的媒体文件存放在 CDN 服务器上，并通过本接口对媒体文件进行点播转码，改变源文件的编码格式、分辨率和码率等属性，在不同终端、网络环境中进行播放。

        <Warning title="注意">
        首次使用本接口之前，请确认是否已经开通 CDN 录制服务。若未开通，请前往 [ZEGO 控制台](https://console.zego.im) 自助开通，详情请参考 [控制台 - 服务配置 - CDN](/console/service-configuration/activate-cdn-service)，或联系 ZEGO 技术支持开通，并配置回调地址，媒体文件转码完成后会通过 [点播转码完成回调](/real-time-video-server/callback/cdn/on-demand-transcoding-completed) 通知。
        </Warning>
        
        开发者可以通过 [点播转码完成回调](/real-time-video-server/callback/cdn/on-demand-transcoding-completed) 或 [查询媒体文件任务](/real-time-video-server/api-reference/cdn/describe-media-task) 接口，查看转码任务的状态、文件回放地址等详细信息。
        
        <Note title="调用频率限制">同一个 AppID 下所有房间：20 次/秒</Note>
      operationId: start-on-demand-transcoding
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://rtc-api.zego.im?Action=TranscodeMedia
          required: true
          schema: { type: string, enum: [TranscodeMedia] }
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/IsTest'
        - name: Vendor
          in: query
          required: true
          schema: { type: string, enum: [Tencent] }
          description: <p>CDN 厂商名。</p><p>当前仅支持取值为 Tencent：腾讯云。</p>
        - name: FileId
          in: query
          required: true
          schema: { type: string }
          description: |
            需要转码的源文件 ID，可以通过以下方式获取：
            <ul><li><a href="/real-time-video-server/callback/cdn/cdn-record-completed" target="blank">录制文件生成回调</a> 的参数 FileID，仅 CDN 厂商为 Tencent 时会回调该参数。</li><li><a href="/real-time-video-server/callback/cdn/merge-media-completed" target="blank">媒体文件合并完成回调</a> 的参数 file_id。</li><li><a href="/real-time-video-server/api-reference/cdn/search-media" target="blank">检索媒体信息</a> 的参数 FileId。</li></ul>
            
            > **注意**
            >
            > ZEGO 不会对"传入的 FileId 文件是否真实存在"进行验证，请您注意填写正确的 FileId；传入错误的 FileId，响应参数中的 Code 为 1000。
        - name: Resolution
          in: query
          required: true
          schema: { type: string, enum: ["360p","540p","720p"] }
          description: |
            <p>转码后的媒体文件分辨率，有以下取值可选：</p><ul><li>360p</li><li>540p</li><li>720p</li></ul>

            > **注意**
            >
            > 如果您需要自定义文件转码参数，请联系 ZEGO 技术支持配置自定义模板。对于常见的转码规格，默认的各分辨率转码模板对应的参数如下：
            > - 360p：封装格式 MP4，视频编码 H.264，码率 400 kbps，帧率25 fps，音频编码 AAC。
            > - 540p：封装格式 MP4，视频编码 H.264，码率 1000 kbps，帧率 25 fps，音频编码 AAC。
            > - 720p：封装格式 MP4，视频编码 H.264，码率 1800 kbps，帧率 25 fps，音频编码 AAC。
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StartOnDemandTranscodingResponse'

components:
  schemas:
    StartOnDemandTranscodingResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int32
          description: |
              以下仅列出了接口业务逻辑相关的部分返回码，完整返回码请参考 [全局返回码](/real-time-video-server/api-reference/return-codes)。
              <table>
              <thead>
                <tr><th>返回码</th><th>说明</th><th>处理建议</th></tr>
              </thead>
              <tbody>
                <tr><td>0</td><td>请求成功。</td><td>-</td></tr>
                <tr><td>2</td><td>输入参数错误。</td><td>-</td></tr>
                <tr><td>3</td><td>未开通相关权限。</td><td>请联系 ZEGO 技术支持。</td></tr>
                <tr><td>4</td><td>CDN 类型不匹配。</td><td>请检查参数。</td></tr>
                <tr><td>5</td><td>配置错误。</td><td>请联系 ZEGO 技术支持。</td></tr>
                <tr><td>6</td><td>请求过于频繁。</td><td>请稍后重试。</td></tr>
                <tr><td>7</td><td>鉴权失败。</td><td>请检查鉴权参数是否正确。</td></tr>
                <tr><td>1000</td><td>请求失败。</td><td>请联系 ZEGO 技术支持。</td></tr>
                <tr><td>41003</td><td>文件不存在。</td><td>请确认文件格式、文件 ID 等是否正确。</td></tr>
              </tbody>
              </table>
          example: 0
        Message:
          type: string
          description: 操作结果描述。
          example: "success"
        RequestId:
          type: string
          description: 请求 ID，由 ZEGO 服务端返回。
          example: "3574501647605445341"
        Data:
          type: object
          description: 响应数据。
          properties:
            Tencent:
              type: object
              description: 腾讯云返回内容（Vendor 为 Tencent 时返回）。
              properties:
                TaskId:
                  type: string
                  description: 媒体文件转码任务的唯一标识 ID，转码结果可以通过 <a href="!Callback_onDemand_transcoding" target="blank">点播转码完成回调</a> 查看。
                  example: "1500020831-procedurev2-58ed61fcdbb0f78a0bf15cabd8ae4713tt0"
                RequestId:
                  type: string
                  description: 唯一请求 ID，由请求参数 Vendor 取值对应的 CDN 厂商（即 Tencent）返回，定位问题时需要提供该次请求的 RequestId。
                  example: "1413c592-5ad4-404e-bfa1-589c32dbcee8"

