openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact: { name: Real-time Voice/Video API Support, email: support@zegocloud.com }

tags:
  - name: cdn

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags: [cdn]
      summary: TranscodeMedia
      description: 开始点播转码。
      operationId: start-on-demand-transcoding
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://rtc-api.zego.im?Action=TranscodeMedia
          required: true
          schema: { type: string, enum: [TranscodeMedia] }
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/IsTest'
        - name: Vendor
          in: query
          required: true
          schema: { type: string, enum: [Tencent] }
          description: 仅支持腾讯云。
        - name: FileId
          in: query
          required: true
          schema: { type: string }
        - name: Resolution
          in: query
          required: true
          schema: { type: string, enum: ["360p","540p","720p"] }
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StartOnDemandTranscodingResponse'

components:
  schemas:
    StartOnDemandTranscodingResponse:
      type: object
      properties:
        Code: { type: integer, format: int32 }
        Message: { type: string }
        RequestId: { type: string }
        Data:
          type: object
          properties:
            Tencent:
              type: object
              properties:
                TaskId: { type: string }
                RequestId: { type: string }

