openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact: { name: Real-time Voice/Video API Support, email: support@zegocloud.com }

tags:
  - name: cdn

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags: [cdn]
      summary: StopCDNRecord
      description: 停止 CDN 录制。
      operationId: stop-cdn-record
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://rtc-api.zego.im?Action=StopCDNRecord
          required: true
          schema: { type: string, enum: [StopCDNRecord] }
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/IsTest'
        - name: StreamId
          in: query
          required: true
          description: 停止录制的流 ID 列表。
          schema:
            type: array
            items: { type: string }
            minItems: 1
          style: form
          explode: true
        - name: Vendor
          in: query
          required: true
          schema: { type: string, enum: [Tencent, Ws, Huawei] }
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StopCDNRecordResponse'

components:
  schemas:
    StopCDNRecordResponse:
      type: object
      properties:
        Code: { type: integer, format: int32 }
        Message: { type: string }
        RequestId: { type: string }
        Data:
          type: object
          properties:
            Tencent:
              type: array
              items:
                type: object
                properties:
                  StreamName: { type: string }
                  RequestId: { type: string }
                  Code: { type: string }
                  Message: { type: string }
            Ws:
              type: object
              properties:
                call_time: { type: string }
                http_code: { type: integer, format: int32 }
                list:
                  type: array
                  items:
                    type: object
                    properties:
                      http_code: { type: integer, format: int32 }
                      id: { type: string }
                      msg: { type: string }
                      persistentId: { type: string }
                      task: { type: string }
                msg: { type: string, nullable: true }
                trace_id: { type: string }
            Huawei:
              type: array
              items:
                type: object
                properties:
                  StreamName: { type: string }
                  RequestId: { type: string }
                  Code: { type: integer, format: int32 }
                  Message: { type: string }

