openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: Real-time Voice/Video API Support
    email: support@zegocloud.com

tags:
  - name: room

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags:
        - room
      summary: AddStream
      description: 调用本接口可向指定房间增加一路流。
      operationId: add-stream
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://rtc-api.zego.im?Action=AddStream
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [AddStream]
          style: form
          explode: true
        # 公共参数
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/IsTest'
        # 业务参数
        - name: RoomId
          in: query
          description: 房间 ID。
          required: true
          schema:
            type: string
        - name: UserId
          in: query
          description: 用户 ID。
          required: true
          schema:
            type: string
        - name: UserName
          in: query
          description: 用户名。
          required: false
          schema:
            type: string
        - name: StreamId
          in: query
          description: 流 ID，不超过 256 字节。
          required: true
          schema:
            type: string
            maxLength: 256
        - name: StreamTitle
          in: query
          description: |
            流标题，不超过 127 字节。
            使用时，请对该参数内容进行 UrlEncode。
          required: false
          schema:
            type: string
            maxLength: 127
        - name: ExtraInfo
          in: query
          description: 流附加信息，不超过 1024 字节。
          required: false
          schema:
            type: string
            maxLength: 1024
        - name: CensorFlag
          in: query
          description: |
            是否允许送审标识。审核房间流列表时，当前流是否允许审核：
            - 0：允许（默认）。
            - 1：不允许。
          required: false
          schema:
            type: integer
            format: int32
            enum: [0, 1]
            default: 0
      responses:
        "200":
          description: 操作成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddStreamResponse'
              example:
                Code: 0
                Message: success
                RequestId: 4443515903608307334

components:
  schemas:
    AddStreamResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int32
          description: 返回码。
        Message:
          type: string
          description: 操作结果描述。
        RequestId:
          type: string
          description: 请求 ID。

