openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: Real-time Voice/Video API Support
    email: support@zegocloud.com

tags:
  - name: room

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags:
        - room
      summary: CloseRoom
      description: 调用本接口将把房间内所有用户从房间移出，并关闭房间。
      operationId: close
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://rtc-api.zego.im?Action=CloseRoom
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [CloseRoom]
          style: form
          explode: true
        # 公共参数
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/IsTest'
        # 业务参数
        - name: RoomId
          in: query
          description: 房间 ID。
          required: true
          allowEmptyValue: false
          schema:
            type: string
        - name: CustomReason
          in: query
          description: |
            关闭原因，最大长度为 256 字节。
            使用时，请对该参数内容进行 UrlEncode。
          required: false
          allowEmptyValue: false
          schema:
            type: string
        - name: RoomCloseCallback
          in: query
          description: |
            是否产生 房间关闭回调，默认为 false。
            由于通常是开发者主动发起的关闭行为，故不再另行通过 房间关闭回调 通知开发者。如果您需要通过 房间关闭回调 进行统一的逻辑处理，可自行修改为 true。
            该参数只影响是否产生 房间关闭回调，其他原因导致房间关闭的回调通知（例如 退出房间回调）不受影响。
          required: false
          schema:
            type: boolean
      responses:
        "200":
          description: 操作成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CloseRoomResponse'
              example:
                Code: 0
                Message: success
                RequestId: TestRequestId1642755866616219000

components:
  schemas:
    CloseRoomResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int32
          description: 返回码。
          example: 0
        Message:
          type: string
          description: 操作结果描述。
          example: success
        RequestId:
          type: string
          description: 请求 ID。
          example: TestRequestId1642755866616219000

