openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: Real-time Voice/Video API Support
    email: support@zegocloud.com

tags:
  - name: room

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags:
        - room
      summary: CloseRoom
      description: |
        调用本接口将把房间内所有用户从房间移出，并关闭房间。

        如果开发者已参考 [回调配置说明](/real-time-video-server/callback/receiving-callback)，配置了 [退出房间回调](/real-time-video-server/callback/room/logged-out)、[流关闭回调](/real-time-video-server/callback/stream/destroyed)，服务端调用本接口时：

        - 服务端会收到 [退出房间回调](/real-time-video-server/callback/room/logged-out) 通知，开发者可以了解用户退出房间的情况。
        - 原房间内的流的状态为关闭，服务端会收到 [流关闭回调](/real-time-video-server/callback/stream/destroyed)，开发者可以知悉有关房间内流关闭的信息。

        房间关闭后，客户端用户会被踢出房间，会收到 ZEGO SDK 回调接口：

        | |ZegoExpress SDK|LiveRoom SDK|
        |-|-|-|
        |iOS/macOS| onRoomStateChanged | onKickout |
        |Android| onRoomStateChanged | onKickout |
        |Windows| onRoomStateChanged | OnKickOut |
        |Web| roomStateChanged | onKickout |

        <Note title="调用频率限制">同一个 AppID 下所有房间：1 次/秒（测试环境：1 次/秒）</Note>

      operationId: close
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://rtc-api.zego.im?Action=CloseRoom
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [CloseRoom]
          style: form
          explode: true
        # 公共参数
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/IsTest'
        # 业务参数
        - name: RoomId
          in: query
          description: 房间 ID。
          required: true
          allowEmptyValue: false
          schema:
            type: string
        - name: CustomReason
          in: query
          description: |
            关闭原因，最大长度为 256 字节。
            使用时，请对该参数内容进行 UrlEncode。
          required: false
          allowEmptyValue: false
          schema:
            type: string
        - name: RoomCloseCallback
          in: query
          default: false
          description: |
            是否产生 [房间关闭回调]()。
            由于通常是开发者主动发起的关闭行为，故不再另行通过 房间关闭回调 通知开发者。如果您需要通过 房间关闭回调 进行统一的逻辑处理，可自行修改为 true。
            > **📌 注意**
            >
            > 该参数只影响是否产生 房间关闭回调，其他原因导致房间关闭的回调通知（例如 [退出房间回调]()）不受影响。
          required: false
          schema:
            type: boolean
      responses:
        "200":
          description: 操作成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CloseRoomResponse'

components:
  schemas:
    CloseRoomResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int32
          description: |
            返回码。以下仅列出了接口业务逻辑相关的部分返回码，完整返回码请参考 [全局返回码](/real-time-video-server/api-reference/return-codes)。

            <table>
              <thead>
                <tr>
                  <th>返回码</th>
                  <th>说明</th>
                  <th>处理建议</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>5018</td>
                  <td>房间已销毁或不存在。</td>
                  <td>请确认请求房间 RoomId 是否存在。</td>
                </tr>
                <tr>
                  <td>5024</td>
                  <td>房间不存在，与 104、50001 内部判断逻辑相同。</td>
                  <td>请确认请求房间 RoomId 是否存在。</td>
                </tr>
              </tbody>
            </table>
          example: 0
        Message:
          type: string
          description: 操作结果描述。
          example: success
        RequestId:
          type: string
          description: 请求 ID。
          example: TestRequestId1642755866616219000

