openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: Real-time Voice/Video API Support
    email: support@zegocloud.com

tags:
  - name: room

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags:
        - room
      summary: DeleteStream
      description: 调用本接口删除某个房间的指定流。
      operationId: delete-stream
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://rtc-api.zego.im?Action=DeleteStream
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [DeleteStream]
          style: form
          explode: true
        # 公共参数
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/IsTest'
        # 业务参数
        - name: RoomId
          in: query
          description: 房间 ID。
          required: true
          schema:
            type: string
        - name: UserId
          in: query
          description: 用户 ID。
          required: true
          schema:
            type: string
        - name: UserName
          in: query
          description: 用户名。
          required: false
          schema:
            type: string
        - name: StreamId
          in: query
          description: 流 ID。
          required: true
          schema:
            type: string
      responses:
        "200":
          description: 操作成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteStreamResponse'
              example:
                Code: 0
                Message: success
                RequestId: 5885338326725063742

components:
  schemas:
    DeleteStreamResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int32
          description: 返回码。
        Message:
          type: string
          description: 操作结果描述。
        RequestId:
          type: string
          description: 请求 ID。

