openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: Real-time Voice/Video API Support
    email: support@zegocloud.com

tags:
  - name: room

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags:
        - room
      summary: DescribeUserNum
      description: |
        调用本接口获取房间人数。

        <Note title="调用频率限制">同一个 AppID 下所有房间：10 次/秒（测试环境：1 次/秒）</Note>
      operationId: describe-user-num
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://rtc-api.zego.im?Action=DescribeUserNum
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [DescribeUserNum]
          style: form
          explode: true
        # 公共参数
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        # 业务参数
        - name: RoomId
          in: query
          description: 房间 ID 列表，一次调用最大支持 10 个房间。当房间不存在时，人数为 0。 示例：RoomId[]=room1&RoomId[]=room2
          required: true
          allowEmptyValue: false
          schema:
            type: array
            items:
              type: string
            minItems: 1
            maxItems: 10
            example: ["room1", "room2"]
          style: form
          explode: true
      responses:
        "200":
          description: 操作成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DescribeUserNumResponse'
              example:
                Code: 0
                Message: success
                RequestId: 7840039829955402142
                Data:
                  UserCountList:
                    - RoomId: room1
                      UserCount: 2
                      AdminUserCount: 0
                    - RoomId: room2
                      UserCount: 3
                      AdminUserCount: 1

components:
  schemas:
    DescribeUserNumResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int32
          description: 返回码。请参考 [全局返回码](/real-time-video-server/api-reference/return-codes)。
          example: 0
        Message:
          type: string
          description: 操作结果描述。
          example: success
        RequestId:
          type: string
          description: 请求 ID。
          example: "7840039829955402142"
        Data:
          type: object
          properties:
            UserCountList:
              type: array
              description: 房间及人数列表。
              items:
                type: object
                properties:
                  RoomId:
                    type: string
                    description: 房间 ID。
                  UserCount:
                    type: integer
                    format: int32
                    description: 房间人数。
                  AdminUserCount:
                    type: integer
                    format: int32
                    description: 房间管理员人数。该参数主要应用于云录制、音视频流审核等场景中；如果房间没有此类用户，请忽略该参数。**请注意，UserCount 中包含了 AdminUserCount 的人数**。

