openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: Real-time Voice/Video API Support
    email: support@zegocloud.com

tags:
  - name: room

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags:
        - room
      summary: DescribeSimpleStreamList
      description: 调用本接口获取房间内流列表信息。
      operationId: describe-simple-streamlist
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://rtc-api.zego.im?Action=DescribeSimpleStreamList
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [DescribeSimpleStreamList]
          style: form
          explode: true
        # 公共参数
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/IsTest'
        # 业务参数
        - name: RoomId
          in: query
          description: 房间 ID。
          required: true
          allowEmptyValue: false
          schema:
            type: string
      responses:
        "200":
          description: 操作成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DescribeSimpleStreamListResponse'
              example:
                Code: 0
                Message: success
                RequestId: 5885338326725063742
                Data:
                  StreamList:
                    - StreamId: stream_demo
                      UserId: user_demo
                      UserName: user_name_demo
                      CreateTime: 1642045110123
                      StreamNumberId: 10

components:
  schemas:
    DescribeSimpleStreamListResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int32
          description: 返回码。
        Message:
          type: string
          description: 操作结果描述。
        RequestId:
          type: string
          description: 请求 ID。
        Data:
          type: object
          properties:
            StreamList:
              type: array
              description: 流列表。
              items:
                type: object
                properties:
                  StreamId:
                    type: string
                    description: 流 ID。
                  UserId:
                    type: string
                    description: 用户名。
                  UserName:
                    type: string
                    description: 用户昵称。
                  CreateTime:
                    type: integer
                    format: int64
                    description: 创建时间。
                  StreamNumberId:
                    type: integer
                    format: uint32
                    description: 房间内流序号。

