openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: Real-time Voice/Video API Support
    email: support@zegocloud.com

tags:
  - name: room

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags:
        - room
      summary: DescribeUsers
      description: |
        调用本接口，可以查询某一房间内的用户的基本状态，包括用户是否在房间、用户的角色、登录房间的时间等。

        <Note title="调用频率限制">同一个 AppID 下所有房间：10 次/秒</Note>
      operationId: describe-users
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://rtc-api.zego.im?Action=DescribeUsers
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [DescribeUsers]
          style: form
          explode: true
        # 公共参数
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        # 业务参数
        - name: RoomId
          in: query
          description: 房间 ID。
          required: true
          allowEmptyValue: false
          schema:
            type: string
        - name: UserId
          in: query
          description: 需要查询状态的用户 ID 列表，最大支持 10 个用户 ID。
          required: true
          schema:
            type: array
            items:
              type: string
            minItems: 1
            maxItems: 10
            example: ["a", "b"]
          style: form
          explode: true
      responses:
        "200":
          description: 操作成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DescribeUsersResponse'
              example:
                Code: 0
                Data:
                  UserStatusList:
                    - UserId: a
                      Status: 1
                      LoginTime: 1675674019365
                      UserRole: 1
                    - UserId: b
                      Status: 1
                      LoginTime: 1675674019455
                      UserRole: 1
                Message: success
                RequestId: TestRequestId1675674022729915000

components:
  schemas:
    DescribeUsersResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int32
          description: |
            返回码。以下仅列出了接口业务逻辑相关的部分返回码，完整返回码请参考 [全局返回码](/real-time-video-server/api-reference/return-codes)。

            <table>
              <thead>
                <tr>
                  <th>返回码</th>
                  <th>说明</th>
                  <th>处理建议</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>2</td>
                  <td>输入参数错误。</td>
                  <td>-</td>
                </tr>
                <tr>
                  <td>3</td>
                  <td>输入参数长度过长。</td>
                  <td>请重新输入参数。</td>
                </tr>
                <tr>
                  <td>206</td>
                  <td>App 请求 QPS 过高被限制。</td>
                  <td>降低请求频率，或联系 ZEGO 技术支持提高 QPS 限制阈值。</td>
                </tr>
                <tr>
                  <td>50001</td>
                  <td>
                    房间不存在。</br></br>
                    <b>📌说明:</b>
                    <ul>
                      <li>1. 当房间内没有用户时，房间会被服务端自动销毁。</li>
                      <li>2. 当房间内只有一个用户时，该用户退出房间或被踢出房间，房间会被服务端自动销毁。</li>
                      <li>3. 当用户心跳请求超时 100 秒后，用户会掉线；所有用户都不在房间后，房间会被服务端自动销毁。</li>
                    </ul>
                  </td>
                  <td>请确认请求房间 RoomId 是否存在。</td>
                </tr>
              </tbody>
            </table>

        Message:
          type: string
          description: 操作结果描述。
        RequestId:
          type: string
          description: 请求 ID。
        Data:
          type: object
          properties:
            UserStatusList:
              type: array
              description: 用户状态列表。
              items:
                type: object
                properties:
                  UserId:
                    type: string
                    description: 用户 ID。
                  Status:
                    type: integer
                    format: uint32
                    description: 用户状态。0：不在房间。1：在房间内。
                  LoginTime:
                    type: integer
                    format: int64
                    description: 该用户登录房间的时间，Unix 毫秒时间戳。
                  UserRole:
                    type: integer
                    format: uint32
                    description: |
                      用户角色。
                      - 1：主播。
                      - 2：观众。
                      - 4：管理员，该类型用户主要存在于云录制、音视频流审核等场景中，客户端 SDK 的用户相关接口会过滤该类型用户。

                      **该返回参数，仅在接入 LiveRoom 服务时有实际意义，接入 Express 服务时请忽略此参数。**

