openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: Real-time Voice/Video API Support
    email: support@zegocloud.com

tags:
  - name: room

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags:
        - room
      summary: KickoutUser
      description: 调用本接口踢出房间内的指定用户。
      operationId: kick-out-user
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://rtc-api.zego.im?Action=KickoutUser
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [KickoutUser]
          style: form
          explode: true
        # 公共参数
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/IsTest'
        # 业务参数
        - name: RoomId
          in: query
          description: 房间 ID。
          required: true
          schema:
            type: string
        - name: UserId
          in: query
          description: 踢出房间的用户 ID 列表，最大支持 5 个用户 ID。
          required: true
          schema:
            type: array
            items:
              type: string
            minItems: 1
            maxItems: 5
          style: form
          explode: true
        - name: CustomReason
          in: query
          description: 踢人原因，最大长度为 256 字节。使用时，请对该参数内容进行 UrlEncode。
          required: false
          schema:
            type: string
            maxLength: 256
      responses:
        "200":
          description: 操作成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KickoutUserResponse'
              example:
                Code: 0
                Message: success
                RequestId: 343649807833778782

components:
  schemas:
    KickoutUserResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int32
          description: 返回码。
        Message:
          type: string
          description: 操作结果描述。
        RequestId:
          type: string
          description: 请求 ID。

