openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: Real-time Voice/Video API Support
    email: support@zegocloud.com

tags:
  - name: room

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags:
        - room
      summary: KickoutUser
      description: |
        调用本接口踢出房间内的指定用户，该用户当前的推流和拉流会全部停止。多用于内容审核场景下，开发者后台发现某个用户的直播内容违规时，可通过本接口将该用户踢出房间。

        客户端被踢的用户会收到 ZEGO SDK 回调接口：

        | |ZegoExpress SDK|LiveRoom SDK|
        |-|-|-|
        |iOS/macOS| onRoomStateChanged | onKickOut |
        |Android| onRoomStateChanged | onKickOut |
        |Windows| onRoomStateChanged |  OnKickOut |
        |Web/小程序| roomStateChanged | onKickOut |


        客户端接收房间内用户变更的通知使用 ZEGO Express SDK 回调接口：

        | |ZegoExpress SDK|LiveRoom SDK|
        |-|-|-|
        |iOS/macOS| onRoomUserUpdate | onUserUpdate |
        |Android| onRoomUserUpdate | onUserUpdate |
        |Windows| onRoomUserUpdate |  OnUserUpdate |
        |Web/小程序| roomUserUpdate | onUserStateUpdate |

        <Note title="调用频率限制">同一个 AppID 下所有房间：50 次/秒</Note>

      operationId: kick-out-user
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://rtc-api.zego.im?Action=KickoutUser
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [KickoutUser]
          style: form
          explode: true
        # 公共参数
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/IsTest'
        # 业务参数
        - name: RoomId
          in: query
          description: 房间 ID。
          required: true
          schema:
            type: string
        - name: UserId
          in: query
          description: 踢出房间的用户 ID 列表，最大支持 5 个用户 ID。
          required: true
          schema:
            type: array
            items:
              type: string
            minItems: 1
            maxItems: 5
          style: form
          explode: true
        - name: CustomReason
          in: query
          description: 踢人原因，最大长度为 256 字节。使用时，需对其内容执行 URL 编码（UrlEncode）处理。
          required: false
          schema:
            type: string
            maxLength: 256
      responses:
        "200":
          description: 操作成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KickoutUserResponse'

components:
  schemas:
    KickoutUserResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int32
          example: 0
          description: |
            以下仅列出了接口业务逻辑相关的部分返回码，完整返回码请参考 [全局返回码](/real-time-video-server/api-reference/return-codes)。

            <table>
              <thead>
                <tr>
                  <th>返回码</th>
                  <th>说明</th>
                  <th>处理建议</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>50011</td>
                  <td>用户列表长度过长。</td>
                  <td>请检查请求包中的用户个数是否超过限制。</td>
                </tr>
              </tbody>
            </table>

        Message:
          type: string
          example: success
          description: 操作结果描述。
        RequestId:
          type: string
          example: 343649807833778782
          description: 请求 ID。

