openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: Real-time Voice/Video API Support
    email: support@zegocloud.com

tags:
  - name: room

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags:
        - room
      summary: SendCustomCommand
      description: 调用本接口在房间内推送自定义消息。
      operationId: send-custom-command
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://rtc-api.zego.im?Action=SendCustomCommand
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [SendCustomCommand]
          style: form
          explode: true
        # 公共参数
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/IsTest'
        # 业务参数
        - name: RoomId
          in: query
          description: 房间 ID。
          required: true
          schema:
            type: string
        - name: FromUserId
          in: query
          description: 发送方用户 ID。
          required: true
          schema:
            type: string
        - name: ToUserId
          in: query
          description: 自定义消息目的用户 ID，最大支持 10 个目的用户 ID。不填表示广播给房间内所有用户。
          required: false
          schema:
            type: array
            items:
              type: string
            minItems: 1
            maxItems: 10
          style: form
          explode: true
        - name: MessageContent
          in: query
          description: 自定义消息内容，长度不能超过 1024 个字节。使用时，请对该参数内容进行 UrlEncode。
          required: true
          schema:
            type: string
            maxLength: 1024
      responses:
        "200":
          description: 操作成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendCustomCommandResponse'
              example:
                Code: 0
                Message: success
                RequestId: 3005402395393320157
                Data:
                  FailUsers:
                    - Uid: "1111"
                      Code: 50003

components:
  schemas:
    SendCustomCommandResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int32
          description: 返回码。
        Message:
          type: string
          description: 操作结果描述。
        RequestId:
          type: string
          description: 请求 ID。
        Data:
          type: object
          properties:
            FailUsers:
              type: array
              description: 处理失败的目标用户 ID 列表。
              items:
                type: object
                properties:
                  Uid:
                    type: string
                    description: 用户 ID。
                  Code:
                    type: integer
                    format: int32
                    description: 失败的错误码（不在线：50003）。

