openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: Real-time Voice/Video API Support
    email: support@zegocloud.com

tags:
  - name: room

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags:
        - room
      summary: SendBarrageMessage
      description: 调用本接口在房间内推送弹幕消息。
      operationId: send-barrage-message
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://rtc-api.zego.im?Action=SendBarrageMessage
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [SendBarrageMessage]
          style: form
          explode: true
        # 公共参数
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/IsTest'
        # 业务参数
        - name: RoomId
          in: query
          description: 房间 ID。
          required: true
          schema:
            type: string
        - name: UserId
          in: query
          description: 发送方用户 ID。
          required: true
          schema:
            type: string
        - name: UserName
          in: query
          description: 发送方用户名（与 UserId 一一对应）。
          required: false
          schema:
            type: string
        - name: MessageCategory
          in: query
          description: 消息分类。1：系统消息。2：聊天消息。
          required: true
          schema:
            type: integer
            format: uint32
            enum: [1, 2]
        - name: MessageContent
          in: query
          description: 消息内容，长度不能超过 1024 个字节。使用时，请对该参数内容进行 UrlEncode。
          required: true
          schema:
            type: string
            maxLength: 1024
      responses:
        "200":
          description: 操作成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendBarrageMessageResponse'
              example:
                Code: 0
                Data:
                  MessageId: 1_1611647493487_29
                Message: success
                RequestId: 2237080460466033406

components:
  schemas:
    SendBarrageMessageResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int32
          description: 返回码。
        Message:
          type: string
          description: 操作结果描述。
        RequestId:
          type: string
          description: 请求 ID。
        Data:
          type: object
          properties:
            MessageId:
              type: string
              description: 消息 ID。

