openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: Real-time Voice/Video API Support
    email: support@zegocloud.com

tags:
  - name: room

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags:
        - room
      summary: SendCustomCommand
      description: |
        调用本接口在房间内推送自定义消息，即向同一房间内指定的单个或多个用户发送信令消息。

        客户端接收消息使用 ZEGO Express SDK 回调接口：

        | 平台 |ZegoExpress SDK|LiveRoom SDK|
        |-|-|-|
        |iOS/macOS| onIMRecvCustomCommand | onReceiveCustomCommand |
        |Android| onIMRecvCustomCommand | onRecvCustomCommand |
        |Windows| onIMRecvCustomCommand |   OnRecvCustomCommand |
        |Web| IMRecvCustomCommand | onRecvCustomCommand |

        <Note title="调用频率限制">同一个 AppID 下所有房间：100 次/秒（测试环境：10 次/秒）</Note>
        <Warning title="注意">
        - 在服务端通过某个 FromUserId 发送消息时，使用相同 FromUserId 的客户端不会收到该条消息，即发送方不能接收到自己发送的消息。
        - 如果开发者需要让房间内的所有用户都收到消息，调用本接口时，应传入该房间用户之外的 FromUserId。
        - 使用的 FromUserId 无需登录该房间，即可直接发送消息。
        </Warning>

      operationId: send-custom-command
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://rtc-api.zego.im?Action=SendCustomCommand
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [SendCustomCommand]
          style: form
          explode: true
        # 公共参数
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        # 业务参数
        - name: RoomId
          in: query
          description: 房间 ID。
          required: true
          schema:
            type: string
        - name: FromUserId
          in: query
          description: 发送方用户 ID。
          required: true
          schema:
            type: string
        - name: ToUserId
          in: query
          description: |
            自定义消息目的用户 ID，最大支持 10 个目的用户 ID。
            如果不填写该参数，自定义消息广播给房间内所有用户；如果填写了该参数，自定义消息只推送到目的用户。
            示例：ToUserId[]=user1&ToUserId[]=user2
          required: false
          schema:
            type: array
            items:
              type: string
            minItems: 1
            maxItems: 10
          style: form
          explode: true
        - name: MessageContent
          in: query
          description: 自定义消息内容，长度不能超过 1024 个字节。使用时，需对其内容执行 URL 编码（UrlEncode）处理。
          required: true
          schema:
            type: string
            maxLength: 1024
      responses:
        "200":
          description: 操作成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendCustomCommandResponse'

components:
  schemas:
    SendCustomCommandResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int32
          example: 0
          description: |
            返回码。以下仅列出了接口业务逻辑相关的部分返回码，完整返回码请参考 [全局返回码](/real-time-video-server/api-reference/return-codes)。

            <table>
              <thead>
                <tr>
                  <th>返回码</th>
                  <th>说明</th>
                  <th>处理建议</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>50003</td>
                  <td>查找用户在线信息失败。</td>
                  <td>请确认请求用户 UserId 是否在线。</td>
                </tr>
                <tr>
                  <td>50011</td>
                  <td>用户列表长度过长。</td>
                  <td>请检查请求包中的用户个数是否超过限制。</td>
                </tr>
                <tr>
                  <td>50012</td>
                  <td>消息长度超过限制。</td>
                  <td>请检查参数长度是否超过限制。</td>
                </tr>
                <tr>
                  <td>50013</td>
                  <td>发送自定义消息失败。</td>
                  <td>请重试，或联系 ZEGO 技术支持处理。</td>
                </tr>
              </tbody>
            </table>
        Message:
          type: string
          example: success
          description: 操作结果描述。
        RequestId:
          type: string
          example: 3005402395393320157
          description: 请求 ID。
        Data:
          type: object
          properties:
            FailUsers:
              type: array
              description: 处理失败的目标用户 ID 列表。
              items:
                type: object
                properties:
                  Uid:
                    type: string
                    example: "1111"
                    description: 用户 ID。
                  Code:
                    type: integer
                    format: int32
                    example: 50003
                    description: 失败的错误码（不在线：50003）。

