openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: Real-time Voice/Video API Support
    email: support@zegocloud.com

tags:
  - name: room

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags:
        - room
      summary: SetForbidUserRule
      description: 设置用户封禁规则。
      operationId: set-forbid-user-rule
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://rtc-api.zego.im?Action=SetForbidUserRule
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [SetForbidUserRule]
          style: form
          explode: true
        # 公共参数
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/IsTest'
        # 业务参数
        - name: RuleType
          in: query
          description: 封禁规则类型：1：通过 IP 地址封禁用户；2：通过 RoomId 封禁用户；3：通过 UserId 封禁用户；4：通过 RoomId 和 UserId 封禁用户。
          required: true
          schema:
            type: integer
            format: int32
            enum: [1, 2, 3, 4]
        - name: IP
          in: query
          description: IP 地址。RuleType 为 1 时必填。
          required: false
          schema:
            type: string
        - name: RoomId
          in: query
          description: 房间 ID。RuleType 为 2、4 时必填。
          required: false
          schema:
            type: string
        - name: UserId
          in: query
          description: 用户 ID。RuleType 为 3、4 时必填。
          required: false
          schema:
            type: string
        - name: DisabledPrivilege
          in: query
          description: 封禁用户所能使用的功能。1：登录。2：推流。
          required: true
          schema:
            type: array
            items:
              type: integer
              format: int32
              enum: [1, 2]
            minItems: 1
          style: form
          explode: true
        - name: EffectiveTime
          in: query
          description: 封禁规则有效时长，单位：秒，取值范围 1 ～ 86400（1 天）。
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
            maximum: 86400
      responses:
        "200":
          description: 操作成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SetForbidUserRuleResponse'
              example:
                Code: 0
                Message: success
                RequestId: TestRequestId1675674022729915000
                Data:
                  ExpireTime: 1704282648

components:
  schemas:
    SetForbidUserRuleResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int32
          description: 返回码。
        Message:
          type: string
          description: 操作结果描述。
        RequestId:
          type: string
          description: 请求 ID。
        Data:
          type: object
          properties:
            ExpireTime:
              type: integer
              format: int64
              description: 封禁规则的过期时间，Unix 时间戳，单位：秒。

