openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: AI Agent API Support
    email: support@zegocloud.com

servers:
  - url: https://aigc-aiagent-api.zegotech.cn
    description: 统一接入地址（不区分区域）
  - url: https://aigc-aiagent-api-sha.zegotech.cn
    description: 中国大陆（上海）

tags:
  - name: agent-configuration-management

paths:
  /:
    post:
      tags:
        - agent-configuration-management
      summary: ListAgents
      description: 通过向本接口，您可以获取可用的智能体列表。
      operationId: list-agents
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://aigc-aiagent-api.zegotech.cn?Action=ListAgents
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [ListAgents]
          style: form
          explode: true
        # 引用共享的参数
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ListAgentsRequest"
            example:
              Limit: 10
              Cursor: ""
      responses:
        "200":
          description: 获取成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListAgentsResponse"
              example:
                Code: 0
                Message: "Success"
                RequestId: "8825223157230377926"
                Data:
                  Total: 10
                  Agents:
                    - AgentId: "xiaozhi"
                      Name: "小智"
                      LLM:
                        Url: "https://ark.cn-beijing.volces.com/api/v3/chat/completions"
                        ApiKey: "eexxxxxxxxxxxxxxx"
                        Model: "ep-xxxxxxxxxx"
                        SystemPrompt: "你是小智，成年女性，是**即构科技创造的陪伴助手**，上知天文下知地理，聪明睿智、热情友善。\n对话要求：1、按照人设要求与用户对话。\n2、不能超过100字。"
                      TTS:
                        Vendor: "ByteDance"
                        Params:
                          app:
                            appid: "your_appid"
                            cluster: "volcano_tts"
                            token: "your_token"
                          audio:
                            voice_type: "your_voice_type"
                      ASR: {}
                  Cursor: "COAI"

components:
  schemas:
    ListAgentsRequest:
      type: object
      properties:
        Limit:
          type: integer
          description: 单次拉取多少个智能体信息。如果数值小于 0 或大于 10 ，则接口调用报错。
          minimum: 0
          maximum: 10
          default: 5
          example: 10
        Cursor:
          type: string
          description: 分页拉取标志，第一次不填，之后填上一次返回的 Cursor 值。当返回的 Cursor 为空时，代表智能体列表获取完毕。
          example: ""

    ListAgentsResponse:
      type: object
      properties:
        Code:
          type: integer
          description: 返回码，0 表示成功，其他值表示失败。详情请参考 [返回码](/aiagent-server/api-reference/return-codes) 说明。
          example: 0
        Message:
          type: string
          description: 请求结果说明
          example: "Success"
        RequestId:
          type: string
          description: 请求 ID
          example: "8825223157230377926"
        Data:
          type: object
          properties:
            Total:
              type: integer
              description: 符合查询条件的智能体总数
              example: 10
            Agents:
              type: array
              description: 智能体列表
              items:
                type: object
                properties:
                  AgentId:
                    type: string
                    description: 智能体唯一标识符
                    example: "xiaozhi"
                  Name:
                    type: string
                    description: 智能体名称
                    example: "小智"
                  LLM:
                    $ref: '../shared-components.yaml#/components/schemas/LLM'
                  TTS:
                    $ref: '../shared-components.yaml#/components/schemas/TTS'
                  ASR:
                    $ref: '../shared-components.yaml#/components/schemas/ASR'
            Cursor:
              type: string
              description: 非空仅表示还有智能体的信息未返回，需要将该字段设置到请求参数 *Cursor* 中拉取更多智能体的信息；为空表示已经返回所有智能体的信息。
              example: "COAI"
