openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: AI Agent API Support
    email: support@zegocloud.com

servers:
  - url: https://aigc-aiagent-api.zegotech.cn
    description: 统一接入地址（不区分区域）
  - url: https://aigc-aiagent-api-sha.zegotech.cn
    description: 中国大陆（上海）

tags:
  - name: agent-configuration-management

paths:
  /:
    post:
      tags:
        - agent-configuration-management
      summary: query-agents
      description: 通过本接口，您可以查询智能体信息。
      operationId: queryAgents
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://aigc-aiagent-api.zegotech.cn?Action=QueryAgents
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [QueryAgents]
          style: form
          explode: true
        # 引用共享的参数
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/QueryAgentsRequest"
            example:
              AgentIds: ["xiaozhi", "xiaoming"]
      responses:
        "200":
          description: 查询成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/QueryAgentsResponse"
              example:
                Code: 0
                Message: "success"
                RequestId: "8825223157230377926"
                Data:
                  Agents:
                    - AgentId: "xiaozhi"
                      Name: "小智"
                      LLM:
                        Url: "https://ark.cn-beijing.volces.com/api/v3/chat/completions"
                        ApiKey: "eexxxxxxxxxxxxxxx"
                        Model: "ep-xxxxxxxxxx"
                        SystemPrompt: "你是小智，成年女性，是**即构科技创造的陪伴助手**，上知天文下知地理，聪明睿智、热情友善。"
                      TTS:
                        Vendor: "ByteDance"
                        Params:
                          app:
                            appid: "your_appid"
                            cluster: "volcano_tts"
                            token: "your_token"
                          audio:
                            voice_type: "your_voice_type"
                      ASR: {}

components:
  schemas:
    QueryAgentsRequest:
      type: object
      required:
        - AgentIds
      properties:
        AgentIds:
          type: array
          description: 已注册智能体 ID 列表，长度上限为 10。
          maxItems: 10
          items:
            type: string
          example: ["xiaozhi", "xiaoming"]

    QueryAgentsResponse:
      type: object
      properties:
        Code:
          type: integer
          description: 返回码，0 表示成功，其他值表示失败。详情请参考 [返回码](/aiagent-server/api-reference/return-codes) 说明。
          example: 0
        Message:
          type: string
          description: 请求结果说明
          example: "Success"
        RequestId:
          type: string
          description: 请求 ID
          example: "8825223157230377926"
        Data:
          type: object
          properties:
            Agents:
              type: array
              description: 智能体列表
              items:
                type: object
                properties:
                  AgentId:
                    type: string
                    description: 智能体唯一标识符
                    example: "xiaozhi"
                  Name:
                    type: string
                    description: 智能体名称
                    example: "小智"
                  LLM:
                    $ref: '../shared-components.yaml#/components/schemas/LLM'
                  TTS:
                    $ref: '../shared-components.yaml#/components/schemas/TTS'
                  ASR:
                    $ref: '../shared-components.yaml#/components/schemas/ASR'
