openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: AI Agent API Support
    email: support@zegocloud.com

servers:
  - url: https://aigc-aiagent-api.zegotech.cn
    description: 统一接入地址（不区分区域）
  - url: https://aigc-aiagent-api-sha.zegotech.cn
    description: 中国大陆（上海）

tags:
  - name: agent-configuration-management

paths:
  /:
    post:
      tags:
        - agent-configuration-management
      summary: register-agent
      description: |
        通过向本接口传入基础配置，您可以注册一个智能体（Agent），以用于创建智能体实例。
      operationId: registerAgent
      x-ratelimit-limit: 10
      x-ratelimit-window: 1
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://aigc-aiagent-api.zegotech.cn?Action=RegisterAgent
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [RegisterAgent]
          style: form
          explode: true
        # 引用共享的参数
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterAgentRequest"
            example:
              AgentId: "xiaozhi"
              Name: "小智"
              LLM:
                Url: "https://ark.cn-beijing.volces.com/api/v3/chat/completions"
                ApiKey: "zego_test"
                Model: "doubao-1-5-lite-32k-250115"
                SystemPrompt: "你是小智，成年女性，是**即构科技创造的陪伴助手**，上知天文下知地理，聪明睿智、热情友善。"
              TTS:
                Vendor: "ByteDance"
                Params:
                  app:
                    appid: "zego_test"
                    token: "zego_test"
                    cluster: "volcano_tts"
                  audio:
                    voice_type: "zh_female_qingxinnvsheng_mars_bigtts"
              ASR:
                HotWord: "即构科技|10"
      responses:
        "200":
          description: 注册成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegisterAgentResponse"
              example:
                Code: 0
                Message: "Succeed"
                RequestId: "1843985617336143872"

components:
  schemas:
    RegisterAgentRequest:
      type: object
      required:
        - AgentId
        - LLM
        - TTS
      properties:
        AgentId:
          type: string
          description: 仅支持数字、英文字符、和以下特殊字符：!#$%&()+-:;\<=.>?@[]^_\{}|~,。
          maxLength: 128
          example: "xiaozhi"
        Name:
          type: string
          description: 智能体名称，长度不超过 256 字节。
          maxLength: 256
          example: "小智"
        LLM:
          $ref: '../shared-components.yaml#/components/schemas/LLM'
        TTS:
          $ref: '../shared-components.yaml#/components/schemas/TTS'
        ASR:
          $ref: '../shared-components.yaml#/components/schemas/ASR'

    RegisterAgentResponse:
      type: object
      properties:
        Code:
          type: integer
          description: 返回码，0 表示成功，其他值表示失败。详情请参考 [返回码](/aiagent-server/api-reference/return-codes) 说明。
          example: 0
        Message:
          type: string
          description: 请求结果说明
          example: "success"
        RequestId:
          type: string
          description: 请求 ID
          example: "3151527792559699732"
