openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: AI Agent API Support
    email: support@zegocloud.com

servers:
  - url: https://aigc-aiagent-api.zegotech.cn
    description: 统一接入地址（不区分区域）
  - url: https://aigc-aiagent-api-sha.zegotech.cn
    description: 中国大陆（上海）

tags:
  - name: agent-configuration-management

paths:
  /:
    post:
      tags:
        - agent-configuration-management
      summary: unregister-agent
      description: 通过向本接口传入智能体 ID，您可以注销一个智能体。
      operationId: unregisterAgent
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://aigc-aiagent-api.zegotech.cn?Action=UnregisterAgent
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [UnregisterAgent]
          style: form
          explode: true
        # 引用共享的参数
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UnregisterAgentRequest"
            example:
              AgentId: "xiaozhi"
      responses:
        "200":
          description: 注销成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnregisterAgentResponse"
              example:
                Code: 0
                Message: "success"
                RequestId: "3151527792559699732"

components:
  schemas:
    UnregisterAgentRequest:
      type: object
      required:
        - AgentId
      properties:
        AgentId:
          type: string
          description: 已注册智能体的唯一标识。
          example: "xiaozhi"

    UnregisterAgentResponse:
      type: object
      properties:
        Code:
          type: integer
          description: 返回码，0 表示成功，其他值表示失败。详情请参考 [返回码](/aiagent-server/api-reference/return-codes) 说明。
          example: 0
        Message:
          type: string
          description: 请求结果说明
          example: "Succeed"
        RequestId:
          type: string
          description: 请求 ID
          example: "1843985617336143872"
