openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: Real-time Voice/Video API Support
    email: support@zegocloud.com

tags:
  - name: room

servers:
  $ref: '../../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags:
        - room
      summary: DelForbidStreamRule
      description: |
        删除音视频流封禁规则。
        <Note title="调用频率限制">同一个 AppID 下所有房间：10 次/秒。</Note>
        <Note title="说明">
          - 您可以通过 [查询音视频流封禁规则](./describe-forbid-stream-rules.mdx) 查看对应的音视频流封禁规则是否删除成功。
          - 如果需要删除的流 ID 对应的封禁规则不存在，调用本接口不会报错。
        </Note>
      operationId: del-forbid-stream-rule
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://rtc-api.zego.im?Action=DelForbidStreamRule
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [DelForbidStreamRule]
          style: form
          explode: true
        # 公共参数
        - $ref: '../../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../../shared-components.yaml#/components/parameters/IsTest'
        # 业务参数
        - name: RoomId
          in: query
          description: 房间 ID。
          required: true
          schema:
            type: string
        - name: StreamId
          in: query
          description: 流 ID，最大不超过 256 字节。
          required: true
          schema:
            type: string
            maxLength: 256
      responses:
        "200":
          description: 操作成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DelForbidStreamRuleResponse'

components:
  schemas:
    DelForbidStreamRuleResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int32
          example: 0
          description: |
            返回码。以下仅列出了接口业务逻辑相关的部分返回码，完整返回码请参考 [全局返回码](/real-time-video-server/api-reference/return-codes)。

            <table>
              <thead>
                <tr>
                  <th>返回码</th>
                  <th>说明</th>
                  <th>处理建议</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>0</td>
                  <td>请求成功。</td>
                  <td>-</td>
                </tr>
                <tr>
                  <td>1</td>
                  <td>请求失败。</td>
                  <td>请联系 ZEGO 技术支持处理。</td>
                </tr>
                <tr>
                  <td>2</td>
                  <td>输入参数错误。</td>
                  <td>-</td>
                </tr>
                <tr>
                  <td>9</td>
                  <td>未开通当前接口的使用权限。</td>
                  <td>请联系 ZEGO 技术支持处理。</td>
                </tr>
                <tr>
                  <td>123</td>
                  <td>设置流信息失败。</td>
                  <td>请重试，或联系 ZEGO 技术支持处理。</td>
                </tr>
                <tr>
                  <td>206</td>
                  <td>App 请求 QPS 过高被限制。</td>
                  <td>降低请求频率，或联系 ZEGO 技术支持提高 QPS 限制阈值。</td>
                </tr>
              </tbody>
            </table>
        Message:
          type: string
          example: success
          description: 操作结果描述。
        RequestId:
          type: string
          example: TestRequestId167562222222915000
          description: 请求 ID。
