openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: Real-time Voice/Video API Support
    email: support@zegocloud.com

tags:
  - name: room

servers:
  $ref: '../../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags:
        - room
      summary: DescribeForbidStreamRules
      description: |
        查询音视频流封禁规则。
        <Note title="调用频率限制">同一个 AppID 下所有房间：10 次/秒。</Note>
        <Note title="说明">如果所查询的 StreamId 不存在、或未设置任何音视频流封禁规则，则返回结果中所有字段值将会为 0，如响应示例中的 streamId2。</Note>
        <Warning title="注意">
          调用 `DescribeForbidStreamRules` 接口，可以查询到当前处于有效期内的规则，也可以查询到已失效的规则。**请注意，ZEGO 会不定期清理数据库中的已失效的封禁规则，调用本接口查询得到的失效规则列表可能不完整。**
        </Warning>
      operationId: describe-forbid-stream-rules
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://rtc-api.zego.im?Action=DescribeForbidStreamRules
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [DescribeForbidStreamRules]
          style: form
          explode: true
        # 公共参数
        - $ref: '../../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../../shared-components.yaml#/components/parameters/IsTest'
        # 业务参数
        - name: RoomId
          in: query
          description: 需要查询的房间 ID。
          required: true
          schema:
            type: string
        - name: StreamId
          in: query
          description: 需要查询的流 ID，调用本接口查询时不可超过 10 个流 ID。
          required: true
          schema:
            type: array
            items:
              type: string
            maxItems: 10
            minItems: 1
          style: form
          explode: true
      responses:
        "200":
          description: 操作成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DescribeForbidStreamRulesResponse'
              example:
                Code: 0
                Data:
                  RoomId: room1
                  ForbidStreamRuleList:
                    - StreamId: streamId1
                      DisableAudio: 1
                      DisableVideo: 1
                      CreateTime: 1343313411
                      EffectiveTime: 3600
                    - StreamId: streamId2
                      DisableAudio: 0
                      DisableVideo: 0
                      CreateTime: 0
                      EffectiveTime: 0
                Message: success
                RequestId: TestRequestId1710224543000

components:
  schemas:
    DescribeForbidStreamRulesResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int32
          description: |
            返回码。以下仅列出了接口业务逻辑相关的部分返回码，完整返回码请参考 [全局返回码](/real-time-video-server/api-reference/return-codes)。

            <table>
              <thead>
                <tr>
                  <th>返回码</th>
                  <th>说明</th>
                  <th>处理建议</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>0</td>
                  <td>请求成功。</td>
                  <td>-</td>
                </tr>
                <tr>
                  <td>1</td>
                  <td>请求失败。</td>
                  <td>请联系 ZEGO 技术支持处理。</td>
                </tr>
                <tr>
                  <td>2</td>
                  <td>输入参数错误。</td>
                  <td>-</td>
                </tr>
                <tr>
                  <td>9</td>
                  <td>未开通当前接口的使用权限。</td>
                  <td>请联系 ZEGO 技术支持处理。</td>
                </tr>
                <tr>
                  <td>123</td>
                  <td>设置流信息失败。</td>
                  <td>请重试，或联系 ZEGO 技术支持处理。</td>
                </tr>
                <tr>
                  <td>206</td>
                  <td>App 请求 QPS 过高被限制。</td>
                  <td>降低请求频率，或联系 ZEGO 技术支持提高 QPS 限制阈值。</td>
                </tr>
              </tbody>
            </table>
        Message:
          type: string
          description: 操作结果描述。
        RequestId:
          type: string
          description: 请求 ID。
        Data:
          type: object
          properties:
            RoomId:
              type: string
              description: 房间 ID。
            ForbidStreamRuleList:
              type: array
              description: 查询到的音视频流封禁规则信息列表。
              items:
                $ref: '#/components/schemas/ForbidStreamRule'

    ForbidStreamRule:
      type: object
      properties:
        StreamId:
          type: string
          description: 查询的流 ID。
        DisableAudio:
          type: integer
          format: int32
          description: 流 ID 对应的音频是否封禁。0：不封禁；1：封禁。
          enum: [0, 1]
        DisableVideo:
          type: integer
          format: int32
          description: 流 ID 对应的视频是否封禁。0：不封禁；1：封禁。
          enum: [0, 1]
        CreateTime:
          type: integer
          format: int64
          description: 音视频流封禁规则的创建时间，Unix 时间戳，单位：秒。
        EffectiveTime:
          type: integer
          format: int64
          description: 音视频流封禁规则的有效时间，Unix 时间戳，单位：秒。
