openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: Real-time Voice/Video API Support
    email: support@zegocloud.com

tags:
  - name: room

servers:
  $ref: '../../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags:
        - room
      summary: SetForbidStreamRule
      description: |
        设置音视频流封禁规则。

        设置成功后，您可以 [查询音视频流封禁规则](./describe-forbid-stream-rules.mdx) 或 [删除音视频流封禁规则](./del-forbid-stream-rule.mdx)。

        <Note title="调用频率限制">同一个 AppID 下所有房间：10 次/秒。</Note>
        <Warning title="注意">
        参数 DisableAudio 和 DisableVideo 的使用：
        - 必须至少有一个取值为 1，否则调用本接口会出错。
        - 针对同一条流 ID，如果多次调用本接口设置不同的封禁规则（每次调用接口时的 DisableAudio 和 DisableVideo 参数取值不同），则以最后一次调用接口的参数设置为准。
        </Warning>

      operationId: set-forbid-stream-rule
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://rtc-api.zego.im?Action=SetForbidStreamRule
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [SetForbidStreamRule]
          style: form
          explode: true
        # 公共参数
        - $ref: '../../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../../shared-components.yaml#/components/parameters/IsTest'
        # 业务参数
        - name: RoomId
          in: query
          description: 房间 ID。
          required: true
          schema:
            type: string
        - name: StreamId
          in: query
          description: 流 ID，最大不超过 256 字节。
          required: true
          schema:
            type: string
            maxLength: 256
        - name: DisableAudio
          in: query
          description: 是否封禁音频。0：不封禁（默认）；1：封禁。
          required: false
          schema:
            type: integer
            format: int32
            enum: [0, 1]
            default: 0
        - name: DisableVideo
          in: query
          description: 是否封禁视频。0：不封禁（默认）；1：封禁。
          required: false
          schema:
            type: integer
            format: int32
            enum: [0, 1]
            default: 0
        - name: EffectiveTime
          in: query
          description: 封禁规则有效时长，单位：秒。默认 21600。范围 1 ～ 86400（超过 24 小时的取值将自动调整为 24 小时）。
          required: false
          schema:
            type: integer
            format: int64
            minimum: 1
            maximum: 86400
            default: 21600
      responses:
        "200":
          description: 操作成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SetForbidStreamRuleResponse'

components:
  schemas:
    SetForbidStreamRuleResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int32
          description: |
            返回码。以下仅列出了接口业务逻辑相关的部分返回码，完整返回码请参考 [全局返回码](/real-time-video-server/api-reference/return-codes)。

            <table>
              <thead>
                <tr>
                  <th>返回码</th>
                  <th>说明</th>
                  <th>处理建议</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>0</td>
                  <td>请求成功。</td>
                  <td>-</td>
                </tr>
                <tr>
                  <td>1</td>
                  <td>请求失败。</td>
                  <td>请联系 ZEGO 技术支持处理。</td>
                </tr>
                <tr>
                  <td>2</td>
                  <td>输入参数错误。</td>
                  <td>-</td>
                </tr>
                <tr>
                  <td>9</td>
                  <td>未开通当前接口的使用权限。</td>
                  <td>请联系 ZEGO 技术支持处理。</td>
                </tr>
                <tr>
                  <td>123</td>
                  <td>设置流信息失败。</td>
                  <td>请重试，或联系 ZEGO 技术支持处理。</td>
                </tr>
                <tr>
                  <td>206</td>
                  <td>App 请求 QPS 过高被限制。</td>
                  <td>降低请求频率，或联系 ZEGO 技术支持提高 QPS 限制阈值。</td>
                </tr>
              </tbody>
            </table>
        Message:
          type: string
          description: 操作结果描述。
          example: success
        RequestId:
          type: string
          description: 请求 ID。
          example: TestRequestId167562222222915000
