openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact: { name: Real-time Voice/Video API Support, email: support@zegocloud.com }

tags:
  - name: moderation

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags: [moderation]
      summary: GenerateIdentifyToken
      description: 生成音视频流审核鉴权 Token。
      operationId: generate-identify-token
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://rtc-api.zego.im?Action=GenerateIdentifyToken
          required: true
          schema: { type: string, enum: [GenerateIdentifyToken] }
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/IsTest'
        - name: EffectiveTime
          in: query
          required: false
          schema: { type: integer, format: int64 }
          description: Token 有效时长（秒），默认 3600，最大 30 天。
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenerateIdentifyTokenResponse'

components:
  schemas:
    GenerateIdentifyTokenResponse:
      type: object
      properties:
        Code: { type: integer, format: int32 }
        Message: { type: string }
        RequestId: { type: string }
        Data:
          type: object
          properties:
            IdentifyToken: { type: string }
            RemainTime: { type: integer, format: int64 }

