openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact: { name: Real-time Voice/Video API Support, email: support@zegocloud.com }

tags:
  - name: moderation

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags: [moderation]
      summary: GenerateIdentifyToken
      description: |
        当您使用第三方音视频流审核服务时，您需要通过本接口生成 `IdentifyToken` 并将其传给审核服务提供商，以作鉴权。

        目前支持的厂商包括数美、网易易盾、图谱、依图、火山引擎等厂商，完整对接流程如下：
        
        ### 数美
        
        1. 完成对接数美 [智能音频流识别](https://www.ishumei.com/new/product/tj/audio)、[智能视频流识别](https://www.ishumei.com/new/product/tj/video) 产品。
        2. 调用本服务端接口获取 `IdentifyToken`。
        3. 调用数美 [音频流上传请求接口](https://help.ishumei.com/docs/tj/audioStream/versionV4/async/developDoc) 或 [视频流上传请求接口](https://help.ishumei.com/docs/tj/videoStream/versionV4/requestInterface/developDoc) 发起请求，在请求参数中需将将 `IdentifyToken` 赋值给 `Token`。
        
        ### 网易易盾
        
        1. 完成对接网易易盾 的审核功能 [音视频解决方案](https://support.dun.163.com/documents/594247746924453888?docId=600827338598789120#%E5%8D%B3%E6%9E%84)。
        2. 调用本服务端接口获取 `IdentifyToken`。
        3. 调用网易易盾 [异步检测接口](https://support.dun.163.com/documents/594247746924453888?docId=600827510305206272) 发起请求，在请求参数中需将将 `IdentifyToken` 赋值给 `Token`。
        
        ### 图谱
        
        1. 完成对接图谱 的 [即构语音流异步接口](https://docs-site.cloud.tuputech.com/docs/api/speech/speech-stream/stream-zego/)。
        2. 调用本服务端接口获取 `IdentifyToken`。
        3. 调用图谱 的 [即构语音流异步接口](https://docs-site.cloud.tuputech.com/docs/api/speech/speech-stream/stream-zego/) 发起请求，在请求参数中需将将 `IdentifyToken` 赋值给 `Token`。
        
        ### 依图和火山引擎
        
        1. 完成对接这两家服务提供商的审核功能，详情请联系服务提供商的技术支持。
        2. 调用本服务端接口获取 `IdentifyToken`。
        3. 调用这两家服务提供商的音视频审核接口（详情请联系服务提供商的技术支持）发起请求，在请求参数中需将将 `IdentifyToken` 赋值给 `Token`。
        
        <Warning title="注意">
        - 每个 `IdentifyToken` 仅能用于一次审核请求；每次调用接口开始审核前，请重新生成 1 个 `IdentifyToken` 使用。
        - 不同厂商在实际使用上可能有由于版本更新或其他原因与本文存在差异，建议在使用前联系技术支持确认。
        
        </Warning>
        <Note title="调用频率限制">同一个 AppID 下所有房间：100 次/秒</Note>
        
        以下请求参数列表仅列出了接口请求参数和部分公共参数，完整公共参数列表请参考 [调用方式](./../accessing-server-apis.mdx#公共请求参数) 中的 “公共请求参数”。
      operationId: generate-identify-token
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://rtc-api.zego.im?Action=GenerateIdentifyToken
          required: true
          schema: { type: string, enum: [GenerateIdentifyToken] }
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/IsTest'
        - name: EffectiveTime
          in: query
          required: false
          schema: { type: integer, format: int64 }
          description: |
            流审核鉴权 Token 的有效时长。
            
            单位：秒，默认为 3600 秒；最大不能超过 30 天（即取值不能超过 60 * 60 * 24 * 30）。
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenerateIdentifyTokenResponse'

components:
  schemas:
    GenerateIdentifyTokenResponse:
      type: object
      properties:
        Code: 
          type: integer
          format: int32
          description: |
            返回码。
            请参考 [全局返回码](/real-time-video-server/api-reference/return-codes)。
          example: 0
        Message: 
          type: string
          description: 操作结果描述
          example: "success"
        RequestId: 
          type: string
          description: 请求 ID
          example: "TestRequestId1653536127853122000"
        Data:
          type: object
          description: 响应数据
          properties:
            IdentifyToken:
              type: string
              description: 鉴权 Token
              example: "1234567890asdfasdfzxcvxxxxxxxxxx"
            RemainTime:
              type: integer
              format: int64
              description: |
                Token 的有效时长，指在"有效时长"范围内，可以向“数美”发起音视频流审核；审核任务开始后，正常流审核期间，不会出现审核用户掉线的问题。

                单位：秒，默认为 1 小时（3600 秒）。
              example: 3600

