openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact: { name: Real-time Voice/Video API Support, email: support@zegocloud.com }

tags:
  - name: moderation

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    post:
      tags: [moderation]
      summary: StartCensorVideoV2
      description: 开始视频流审核。
      operationId: start-censor-video
      parameters:
        - name: Action
          in: query
          required: true
          description: |
            > 接口原型参数
            >
            > https://rtc-api.zego.im?Action=StartCensorVideoV2
          schema: { type: string, enum: [StartCensorVideoV2] }
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/IsTest'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StartCensorVideoRequest'
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StartCensorVideoResponse'

components:
  schemas:
    StartCensorVideoRequest:
      type: object
      required: [RoomId, EventId, VideoParam]
      properties:
        RoomId: { type: string }
        EventId: { type: string }
        Language: { type: string, enum: [zh,en,ar] }
        AudioParam:
          type: object
          properties:
            RiskTypeList:
              type: array
              items: { type: string }
            BusinessTypeList:
              type: array
              items: { type: string }
            AudioLanguage:
              type: array
              items: { type: string, enum: [zh,ja,ko,th,vi,ms,tl,id,hi,ar,tr,en,es,pt,it,fr,de,ru] }
            ReturnAllText: { type: integer, format: int32, enum: [0,1], default: 0 }
            ReturnPreText: { type: integer, format: int32, enum: [0,1], default: 0 }
            ReturnPreAudio: { type: integer, format: int32, enum: [0,1], default: 0 }
            ResultCallbackUrl: { type: string }
            StatusCallbackUrl: { type: string }
        VideoParam:
          type: object
          properties:
            RiskTypeList:
              type: array
              items: { type: string }
            BusinessTypeList:
              type: array
              items: { type: string }
            ReturnAllImg: { type: integer, format: int32, enum: [0,1], default: 0 }
            DetectFrequency: { type: integer, format: int32 }
            ResultCallbackUrl: { type: string }
            StatusCallbackUrl: { type: string }
        ReturnFinishInfo: { type: integer, format: int32, enum: [0,1], default: 0 }
    StartCensorVideoResponse:
      type: object
      properties:
        Code: { type: integer, format: int32 }
        Message: { type: string }
        RequestId: { type: string }
        Data:
          type: object
          properties:
            TaskId: { type: string }

