openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: AI Agent API Support
    email: support@zegocloud.com

servers:
  - url: https://aigc-aiagent-api.zegotech.cn
    description: Unified access address (no regional distinction)
  - url: https://aigc-aiagent-api-sha.zegotech.cn
    description: Mainland China (Shanghai)
  - url: https://aigc-aiagent-api-hkg.zegotech.cn
    description: Hong Kong, Macao, and Taiwan (Hong Kong)
  - url: https://aigc-aiagent-api-fra.zegotech.cn
    description: Europe (Frankfurt)
  - url: https://aigc-aiagent-api-lax.zegotech.cn
    description: Western United States (California)
  - url: https://aigc-aiagent-api-bom.zegotech.cn
    description: Asia-Pacific (Mumbai)
  - url: https://aigc-aiagent-api-sgp.zegotech.cn
    description: Southeast Asia (Singapore)

tags:
  - name: agent-instance-control

paths:
  /:
    post:
      tags:
        - agent-instance-control
      summary: ResetAgentInstanceMsgList
      description: This interface is used to reset the message list used as context when interacting with the AI agent instance.
      operationId: reset-agent-instance-msg-list
      parameters:
        - name: Action
          in: query
          description: |
            > API Prototype Parameter
            >
            > https://aigc-aiagent-api.zegotech.cn?Action=ResetAgentInstanceMsgList
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [ResetAgentInstanceMsgList]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ResetAgentInstanceMsgListRequest"
            example:
              AgentInstanceId: "1907755175297171456"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResetAgentInstanceMsgListResponse"

components:
  schemas:
    ResetAgentInstanceMsgListRequest:
      type: object
      required:
        - AgentInstanceId
      properties:
        AgentInstanceId:
          type: string
          description: The unique identifier of the AI agent instance, obtained through the response parameters of the [Create AI Agent Instance](/aiagent-server/api-reference/agent-instance-management/create-agent-instance) interface.
          example: "1907755175297171456"

    ResetAgentInstanceMsgListResponse:
      type: object
      properties:
        Code:
          type: integer
          description: Return code. 0 indicates success, other values indicate failure. For more information on error codes and response handling recommendations, please refer to [Return Codes](/aiagent-server/api-reference/return-codes).
          example: 0
        Message:
          type: string
          description: Explanation of the request result
          example: "Success"
        RequestId:
          type: string
          description: Request ID
          example: "8825223157230377926"
