openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact: { name: Real-time Voice/Video API Support, email: support@zegocloud.com }

tags:
  - name: scene

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags: [scene]
      summary: SetSceneTemplate
      description: 配置 Express 场景模板。
      operationId: set-scene-template
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://metaworld-api.zego.im/?Action=SetSceneTemplate
          required: true
          schema: { type: string, enum: [SetSceneTemplate] }
          style: form
          explode: true
        # 公共参数
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/IsTest'
        # 业务参数（按 mdx）
        - name: TemplateId
          in: query
          required: true
          schema: { type: integer, format: int32 }
          description: 模板 ID。
        - name: LeftBottomX
          in: query
          required: false
          schema: { type: number, format: float }
          description: 地图左下角横坐标。
        - name: LeftBottomZ
          in: query
          required: false
          schema: { type: number, format: float }
          description: 地图左下角纵坐标。
        - name: RightUpX
          in: query
          required: false
          schema: { type: number, format: float }
          description: 地图右上角横坐标。
        - name: RightUpZ
          in: query
          required: false
          schema: { type: number, format: float }
          description: 地图右上角纵坐标。
        - name: MaxUserNum
          in: query
          required: true
          schema: { type: integer, format: int32 }
          description: 场景人数上限。
        - name: ViewRadius
          in: query
          required: true
          schema: { type: integer, format: int32 }
          description: AOI 半径（用户视野半径）。
        - name: MaxVisibleNum
          in: query
          required: true
          schema: { type: integer, format: int32 }
          description: AOI 人数上限（最多 100）。
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SetSceneTemplateResponse'

components:
  schemas:
    SetSceneTemplateResponse:
      type: object
      properties:
        Code: { type: integer, format: int32, description: 错误码 }
        Message: { type: string, description: 错误信息描述 }
        RequestId: { type: string, description: 请求 ID }
        Data:
          nullable: true
          oneOf:
            - type: object
            - type: 'null'
          description: 返回数据内容。

