openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact: { name: Real-time Voice/Video API Support, email: support@zegocloud.com }

tags:
  - name: scene

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags: [scene]
      summary: SetSceneTemplate
      description: |
        Express 支持自定义场景模版配置，用于登录到对应配置的场景。
        当系统预置的配置模板无法满足您的业务需求时，您可以通过该服务端 API 创建自定义模板，设置相关参数。
        
        <Warning title="注意">
        自定义模板上限为 50，如果您需要更多的模板数量，请联系 ZEGO 技术支持。
        </Warning>
        以下请求参数列表仅列出了接口请求参数和部分公共参数，完整公共参数列表请参考 完整公共参数列表请参考 [调用方式](./../accessing-server-apis.mdx#公共请求参数) 中的 “公共请求参数”。

        <Note title="说明">
        测试环境下（详见 <a target="_blank" href="./../accessing-server-apis.mdx#公共请求参数">调用方式</a> 中的 “公共参数” 中的 IsTest 的参数说明），流 ID 需要加上 “zegotest-AppId-” 前缀。例如，流 ID 为 “test”，在 AppId 为 “123456789” 的测试环境下，流 ID 应为 “zegotest-123456789-test”。
        </Note>
        ```
                                -------------------------------------------(RightUpX, RightUpZ)
                                |	                                   |
                                |	                                   |
                                |	                                   |
                                |	                                   |
                                |	                                   |											                
        (LeftBottomX, LeftBottomZ)------------------------------------------
        
        ```
        <Warning title="注意">
        模板配置更改后，正在使用该模板的场景不会立刻生效，需等待场景销毁后（场景中全部用户退出 10 分钟后，该场景会被自动销毁），重新创建才可生效。
        </Warning>
      operationId: set-scene-template
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://metaworld-api.zego.im/?Action=SetSceneTemplate
          required: true
          schema: { type: string, enum: [SetSceneTemplate] }
        # 公共参数
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/IsTest'
        # 业务参数（按 mdx）
        - name: AppId
          in: query
          required: true
          schema: { type: number }
          description: 应用 AppID。
        - name: TemplateId
          in: query
          required: true
          schema: { type: number }
          description: 模板 ID。
        - name: LeftBottomX
          in: query
          required: false
          schema: { type: number, format: float }
          description: 地图左下角横坐标（见上图）。
        - name: LeftBottomZ
          in: query
          required: false
          schema: { type: number, format: float }
          description: 地图左下角纵坐标（见上图）。
        - name: RightUpX
          in: query
          required: false
          schema: { type: number, format: float }
          description: 地图右上角横坐标（见上图）。
        - name: RightUpZ
          in: query
          required: false
          schema: { type: number, format: float }
          description: 地图右上角纵坐标（见上图）。
        - name: MaxUserNum
          in: query
          required: true
          schema: { type: integer, format: int32 }
          description: 场景人数上限。
        - name: ViewRadius
          in: query
          required: true
          schema: { type: integer, format: int32 }
          description: AOI 半径（用户视野半径）。
        - name: MaxVisibleNum
          in: query
          required: true
          schema: { type: integer, format: int32 }
          description: |
            AOI 人数上限
            
            本端用户的AOI范围内，可视远端用户数的上限，人数上限最多 100。
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SetSceneTemplateResponse'

components:
  schemas:
    SetSceneTemplateResponse:
      type: object
      properties:
        Code: 
          type: integer
          format: int32
          description: |
            错误码。
            以下仅列出了接口业务逻辑相关的部分返回码，完整返回码请参考 [全局返回码](!global_return_code)。
            <table>
              <thead>
                <tr><th>返回码</th><th>说明</th><th>处理建议</th></tr>
              </thead>
              <tbody>
                <tr><td>340004003</td><td>模版已存在。</td><td>设置其他模版 ID。</td></tr>
                <tr><td>340006003</td><td>参数错误。</td><td>根据错误提示设置正确的请求参数。</td></tr>
              </tbody>
            </table>
          example: 0
        Message: 
          type: string
          description: 错误信息描述
          example: "succeed"
        RequestId: 
          type: string
          description: 请求 ID
          example: "9f674801-69e9-463f-a966-1ba2c6b5dbbe"
        Data:
          type: object
          nullable: true
          description: 返回数据内容
          example: null

