openapi: 3.0.0
info:
  title: open-api-desc

  version: 1.0.0
  contact:
    name: AI Agent API Support
    email: support@zegocloud.com

servers:
  - url: https://aigc-aiagent-api.zegotech.cn
    description: 统一接入地址（不区分区域）
  - url: https://aigc-aiagent-api-sha.zegotech.cn
    description: 中国大陆（上海）

tags:
  - name: agent-instance-management

paths:
  /:
    post:
      tags:
        - agent-instance-management
      summary: CreateAgentInstance
      description: 通过本接口，您可以创建智能体实例，并将智能体实例加入到语音（RTC）对话之中。
      operationId: create-agent-instance
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://aigc-aiagent-api.zegotech.cn?Action=CreateAgentInstance
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [CreateAgentInstance]
          style: form
          explode: true
        # 引用共享的参数
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateAgentInstanceRequest"
            example:
              AgentId: "xiaozhi"
              UserId: "user_1"
              RTC:
                RoomId: "room_1"
                AgentStreamId: "agent_stream_1"
                AgentUserId: "agent_user_1"
                UserStreamId: "user_stream_1"
      responses:
        "200":
          description: 创建成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateAgentInstanceResponse"
              example:
                Code: 0
                Message: "success"
                RequestId: "3151527792559699732"
                Data:
                  AgentInstanceId: "1912122918452641792"

components:
  schemas:
    CreateAgentInstanceRequest:
      type: object
      required:
        - AgentId
        - UserId
        - RTC
      properties:
        AgentId:
          type: string
          description: 已注册的智能体唯一标识符
          example: "xiaozhi"
        UserId:
          type: string
          description: 用于登录 RTC 房间的真实用户 ID。 仅支持数字、英文字符、'-'、'_'。
          example: "user_1"
          maxLength: 32
        # 引用共享的Schema
        RTC:
          $ref: '../shared-components.yaml#/components/schemas/RTC'
        LLM:
          $ref: '../shared-components.yaml#/components/schemas/LLM'
        TTS:
          $ref: '../shared-components.yaml#/components/schemas/TTS'
        ASR:
          $ref: '../shared-components.yaml#/components/schemas/ASR'
        MessageHistory:
          $ref: '../shared-components.yaml#/components/schemas/MessageHistory'
        CallbackConfig:
          $ref: '../shared-components.yaml#/components/schemas/CallbackConfig'
        AdvancedConfig:
          $ref: '../shared-components.yaml#/components/schemas/AdvancedConfig'

    CreateAgentInstanceResponse:
      type: object
      properties:
        Code:
          type: integer
          description: 返回码，0 表示成功，其他值表示失败。详情请参考 [返回码](/aiagent-server/api-reference/return-codes) 说明。
          example: 0
        Message:
          type: string
          description: 请求结果说明
          example: "Success"
        RequestId:
          type: string
          description: 请求 ID
          example: "3151527792559699732"
        Data:
          type: object
          properties:
            AgentInstanceId:
              type: string
              description: 智能体实例的唯一标识。
              example: "1912122918452641792"
