openapi: 3.0.0
info:
  title: AI Agent API - 创建数字人实例
  description: |
    # 创建数字人 AI Agent 实例
    
    创建一个新的数字人 AI Agent 实例并将其加入到语音（RTC）会话中。
    
    ## 接口调用方式
    
    使用 POST 方法，通过查询参数 `Action=CreateDigitalHumanAgentInstance` 来指定操作。
    
    ## 认证方式
    
    API 使用签名认证方式，请在请求中包含必要的认证参数。
    
  version: 1.0.0
  contact:
    name: AI Agent API Support
    email: support@zegocloud.com

servers:
  - url: https://aigc-aiagent-api.zegotech.cn
    description: 统一接入地址（不区分区域）
  - url: https://aigc-aiagent-api-sha.zegotech.cn
    description: 中国大陆（上海）

tags:
  - name: create-operations
    description: 创建操作

paths:
  /:
    post:
      tags:
        - create-operations
      summary: 创建数字人 AI Agent 实例
      description: 创建一个新的数字人 AI Agent 实例并将其加入到语音（RTC）会话中。
      operationId: createDigitalHumanAgentInstance
      parameters:
        - name: Action
          in: query
          description: 操作类型
          required: true
          schema:
            type: string
            enum: [CreateDigitalHumanAgentInstance]
          example: CreateDigitalHumanAgentInstance
        # 引用共享的参数
        - $ref: 'shared-components.yaml#/components/parameters/AppId'
        - $ref: 'shared-components.yaml#/components/parameters/ServerSecret'
        - $ref: 'shared-components.yaml#/components/parameters/Nonce'
        - $ref: 'shared-components.yaml#/components/parameters/Timestamp'
        - $ref: 'shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateDigitalHumanAgentInstanceRequest"
            example:
              AgentId: "xiaozhi"
              UserId: "user_1"
              RTC:
                RoomId: "room_1"
                AgentStreamId: "agent_stream_1"
                AgentUserId: "agent_user_1"
                UserStreamId: "user_stream_1"
              DigitalHuman:
                DigitalHumanId: "xiaozhi"
                EncodeCode: "H264"
                ConfigId: "mobile"
      responses:
        "200":
          description: 创建成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateDigitalHumanAgentInstanceResponse"
              example:
                Code: 0
                Message: "success"
                RequestId: "3151527792559699732"
                Data:
                  AgentInstanceId: "1912122918452641792"
                  DigitalHumanConfig: "eyJEaWdpdGFsSHVtYW5JZCI6ImU1ODNkMzVmLTk3OTMtNDJiNC1hYjFiLTE4OWEzNWI4OGQxYyIsIlN0cmVhbXMiOlt7IlJvb21JZCI6ImlyXzU1NTd5bDVoIiwiU3RyZWFtSWQiOiJpcl81NTU3eWw1aF8xNzEwMl9hZ2VudCIsIkVuY29kZUNvZGUiOiJIMjY0IiwiQ29uZmlnSWQiOiJ3ZWIifV19"
        "400":
          description: 请求错误
          content:
            application/json:
              schema:
                $ref: 'shared-components.yaml#/components/schemas/ErrorResponse'

components:
  schemas:
    CreateDigitalHumanAgentInstanceRequest:
      allOf:
        - $ref: "#/components/schemas/CreateAgentInstanceRequest"
        - type: object
          properties:
            DigitalHuman:
              $ref: 'shared-components.yaml#/components/schemas/DigitalHuman'

    CreateAgentInstanceRequest:
      type: object
      required:
        - AgentId
        - UserId
        - RTC
      properties:
        AgentId:
          type: string
          description: 已注册的智能体唯一标识符
          example: "xiaozhi"
        UserId:
          type: string
          description: 用于登录 RTC 房间的真实用户 ID
          example: "user_1"
          maxLength: 32
        # 引用共享的Schema
        RTC:
          $ref: 'shared-components.yaml#/components/schemas/RTC'
        LLM:
          $ref: 'shared-components.yaml#/components/schemas/LLM'
        TTS:
          $ref: 'shared-components.yaml#/components/schemas/TTS'
        ASR:
          $ref: 'shared-components.yaml#/components/schemas/ASR'
        MessageHistory:
          $ref: 'shared-components.yaml#/components/schemas/MessageHistory'
        CallbackConfig:
          $ref: 'shared-components.yaml#/components/schemas/CallbackConfig'
        AdvancedConfig:
          $ref: 'shared-components.yaml#/components/schemas/AdvancedConfig'

    CreateDigitalHumanAgentInstanceResponse:
      type: object
      properties:
        Code:
          type: integer
          description: 返回码，0 表示成功，其他值表示失败
          example: 0
        Message:
          type: string
          description: 请求结果说明
          example: "success"
        RequestId:
          type: string
          description: 请求 ID
          example: "3151527792559699732"
        Data:
          type: object
          properties:
            AgentInstanceId:
              type: string
              description: AI Agent 实例的唯一标识符
              example: "1912122918452641792"
            DigitalHumanConfig:
              type: string
              description: 数字人配置信息
              example: "eyJEaWdpdGFsSHVtYW5JZCI6ImU1ODNkMzVmLTk3OTMtNDJiNC1hYjFiLTE4OWEzNWI4OGQxYyIsIlN0cmVhbXMiOlt7IlJvb21JZCI6ImlyXzU1NTd5bDVoIiwiU3RyZWFtSWQiOiJpcl81NTU3eWw1aF8xNzEwMl9hZ2VudCIsIkVuY29kZUNvZGUiOiJIMjY0IiwiQ29uZmlnSWQiOiJ3ZWIifV19"
