openapi: 3.0.0
info:
  title: AI Agent API - 删除实例
  description: |
    # 删除 AI Agent 实例
    
    根据实例ID删除指定的 AI Agent 实例。
    
    ## 接口调用方式
    
    使用 POST 方法，通过查询参数 `Action=DeleteAgentInstance` 来指定操作。
    
    ## 认证方式
    
    API 使用签名认证方式，请在请求中包含必要的认证参数。
    
  version: 1.0.0
  contact:
    name: AI Agent API Support
    email: support@zegocloud.com

servers:
  - url: https://aigc-aiagent-api.zegotech.cn
    description: 统一接入地址（不区分区域）
  - url: https://aigc-aiagent-api-sha.zegotech.cn
    description: 中国大陆（上海）

tags:
  - name: delete-operations
    description: 删除操作

paths:
  /:
    post:
      tags:
        - delete-operations
      summary: 删除 AI Agent 实例
      description: 根据实例ID删除指定的 AI Agent 实例。
      operationId: deleteAgentInstance
      parameters:
        - name: Action
          in: query
          description: 操作类型
          required: true
          schema:
            type: string
            enum: [DeleteAgentInstance]
          example: DeleteAgentInstance
        # 引用共享的参数
        - $ref: 'shared-components.yaml#/components/parameters/AppId'
        - $ref: 'shared-components.yaml#/components/parameters/ServerSecret'
        - $ref: 'shared-components.yaml#/components/parameters/Nonce'
        - $ref: 'shared-components.yaml#/components/parameters/Timestamp'
        - $ref: 'shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeleteAgentInstanceRequest"
            example:
              AgentInstanceId: "1909811657303920640"
      responses:
        "200":
          description: 删除成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeleteAgentInstanceResponse"
              example:
                Code: 0
                Message: "Succeed"
                RequestId: "1843985617336143872"
        "400":
          description: 请求错误
          content:
            application/json:
              schema:
                $ref: 'shared-components.yaml#/components/schemas/ErrorResponse'
        "404":
          description: 实例不存在
          content:
            application/json:
              schema:
                $ref: 'shared-components.yaml#/components/schemas/ErrorResponse'

components:
  schemas:
    DeleteAgentInstanceRequest:
      type: object
      required:
        - AgentInstanceId
      properties:
        AgentInstanceId:
          type: string
          description: AI Agent 实例的唯一标识符
          example: "1909811657303920640"

    DeleteAgentInstanceResponse:
      type: object
      properties:
        Code:
          type: integer
          description: 返回码，0 表示成功，其他值表示失败
          example: 0
        Message:
          type: string
          description: 请求结果说明
          example: "Succeed"
        RequestId:
          type: string
          description: 请求 ID
          example: "1843985617336143872"
