openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: AI Agent API Support
    email: support@zegocloud.com

servers:
  - url: https://aigc-aiagent-api.zegotech.cn
    description: 统一接入地址（不区分区域）
  - url: https://aigc-aiagent-api-sha.zegotech.cn
    description: 中国大陆（上海）

tags:
  - name: agent-instance-management

paths:
  /:
    post:
      tags:
        - agent-instance-management
      summary: UpdateAgentInstance
      description: 通过本接口，您可以更新智能体实例的配置。
      operationId: update-agent-instance
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://aigc-aiagent-api.zegotech.cn?Action=UpdateAgentInstance
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [UpdateAgentInstance]
          style: form
          explode: true
        # 引用共享的参数
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateAgentInstanceRequest"
            example:
              AgentInstanceId: "1907755175297171456"
              LLM:
                Url: "https://ark.cn-beijing.volces.com/api/v3/chat/completions"
                ApiKey: "zego_test"
                Model: "doubao-1-5-lite-32k-250115"
                SystemPrompt: "你是小智，成年女性，是**即构科技创造的陪伴助手**，上知天文下知地理，聪明睿智、热情友善。"
      responses:
        "200":
          description: 更新成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdateAgentInstanceResponse"
              example:
                Code: 0
                Message: "success"
                RequestId: "3151527792559699732"

components:
  schemas:
    UpdateAgentInstanceRequest:
      type: object
      required:
        - AgentInstanceId
      properties:
        AgentInstanceId:
          type: string
          description: 智能体实例的唯一标识，通过 [创建智能体实例](/aiagent-server/api-reference/agent-instance-management/create-agent-instance) 接口的响应参数获取。
          example: "1907755175297171456"
        LLM:
          $ref: '../shared-components.yaml#/components/schemas/LLM'
        TTS:
          $ref: '../shared-components.yaml#/components/schemas/TTS'
        ASR:
          $ref: '../shared-components.yaml#/components/schemas/ASR'

    UpdateAgentInstanceResponse:
      type: object
      properties:
        Code:
          type: integer
          description: 返回码，0 表示成功，其他值表示失败。详情请参考 [返回码](/aiagent-server/api-reference/return-codes) 说明。
          example: 0
        Message:
          type: string
          description: 请求结果说明
          example: "success"
        RequestId:
          type: string
          description: 请求 ID
          example: "3151527792559699732"
