name: 清理 Vercel 排队中部署
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 清理 Vercel 部署
        uses: Match-Yang/vercel-cleanup-action@v1
        with:
          vercel_token: ${{ secrets.VERCEL_CLI_TOKEN }}
          default_projects: "docs-startere7a924ed,docs-starterfa8b328a"
          verbose: true